[skip ci] Correct the release note link and update minor changes in Install dependencies
milvus-io/milvus pull request #102
Opened 2019-10-25 08:35 UTC by jielinxu

2019-10-25 08:39 UTC, yamasite approved these changes

2019-10-26 02:36 UTC, JinHai-CN requested changes

2019-10-26 02:36 UTC, JinHai-CN commented on README.md
> +=======
Why use '======'?

2019-10-26 04:31 UTC, jielinxu commented on README.md
> +=======
Removed it.

2019-10-28 03:03 UTC, merged

2021-11-06 23:08 UTC, abodyy4272 commented on README.md
> +=======
> Removed it.