Update INSTALL.md
milvus-io/milvus pull request #1283
Opened 2020-02-20 07:23 UTC by sahuang

**What type of PR is this?**

documentation

**What this PR does / why we need it:**

Fix CentOS and update troubleshooting details

2020-02-20 07:30 UTC, yamasite commented on INSTALL.md
> +2. Try to reinstall the latest CMake from source with `--system-curl` option:
这里的意思是尝试做，而不是努力做。不应改成to。另外，工程师请将注意力放在技术正确性上。

2020-02-20 07:37 UTC, yamasite requested changes
Please refer to my comment. Thanks.

2020-02-20 07:44 UTC, sahuang commented on INSTALL.md
> +2. Try to reinstall the latest CMake from source with `--system-curl` option:
ok

2020-02-20 07:48 UTC, yamasite approved these changes

2020-02-20 07:50 UTC, yamasite commented on INSTALL.md
> +```c++
Should be shell

2020-02-20 07:51 UTC, yamasite approved these changes

2020-02-20 07:52 UTC, yamasite approved these changes

2020-02-20 07:59 UTC, yamasite commented on INSTALL.md
> +```shell
Please add a dollar sign `$` before a shell command.

2020-02-20 08:00 UTC, yamasite commented on INSTALL.md
>  Try to increase the memory allocated to Docker. If this doesn't work, you can reduce the number of threads in CMake build in `[Milvus root path]/core/build.sh`.
Could you please also use **Try increasing** here? I just noticed this error. I might have overlooked this before.

2020-02-20 08:01 UTC, yamasite requested changes
Please refer to my latest comments.

2020-02-20 08:20 UTC, yamasite approved these changes

2020-02-21 03:54 UTC, yamasite commented
This also fixes #1150 and #1151

2020-02-21 13:19 UTC, merged