Create README_CN.md
milvus-io/milvus pull request #129
Opened 2019-10-30 02:22 UTC by akihoni

中文版readme。

2019-10-30 05:56 UTC, jielinxu approved these changes

2019-10-30 06:50 UTC, yamasite commented on README_CN.md
> +创建 `example.py` 文件，并向文件中加入 [Python 示例代码](https://github.com/milvus-io/pymilvus/blob/master/examples/AdvancedExample.py)。
此链接无效，请更新链接。
https://github.com/milvus-io/pymilvus/blob/master/examples/advanced_example.py

2019-10-30 06:52 UTC, yamasite requested changes
Please fix the broken link before submitting code. Thanks! Please refer to my comment for more information.

2019-10-30 10:35 UTC, akihoni commented on README_CN.md
> +创建 `example.py` 文件，并向文件中加入 [Python 示例代码](https://github.com/milvus-io/pymilvus/blob/master/examples/AdvancedExample.py)。
好的。

2019-10-31 03:46 UTC, akihoni reviewed
更换无效链接，并请求merge到0.5.1。

2019-10-31 06:01 UTC, yamasite commented on README_CN.md
> +![](https://raw.githubusercontent.com/yamasite/docs/master/assets/milvus_arch.png)
请不要使用个人的GitHub仓库作为图片链接地址。请选择Milvus的官方仓库。

2019-10-31 06:02 UTC, yamasite requested changes
关于产品架构图，请不要使用个人的GitHub仓库作为图片链接地址。请选择Milvus的官方仓库。

2019-10-31 06:42 UTC, akihoni commented
已更改图片链接地址。

2019-10-31 07:29 UTC, yamasite approved these changes

2019-11-01 07:17 UTC, merged

2019-12-04 03:50 UTC, jielinxu commented
@all-contributors please add @akihoni for doc