Update README_CN
milvus-io/milvus pull request #138
Opened 2019-10-30 10:38 UTC by akihoni

替换了无效链接。

2019-10-31 03:10 UTC, jielinxu approved these changes

2019-10-31 03:29 UTC, yamasite approved these changes

2019-10-31 03:32 UTC, yamasite requested changes
Please do not directly merge to master. Use 0.5.1 instead.

2019-10-31 03:35 UTC, akihoni commented
Okay.

2019-11-01 02:28 UTC, jielinxu commented
This PR replicates with #129 .

2019-11-01 02:28 UTC, closed without merging