fix README offiline installation.
milvus-io/milvus pull request #16000
Opened 2022-03-10 13:28 UTC by dariocurr

Hi, I am Dario, a developer at [BuildNN](https://github.com/buildnn).
When I tried to start `milvus` with the `docker-compose`, following this [guide ](https://milvus.io/docs/v2.0.x/install_offline-docker.md), I encountered a little error. When I tried to run 
```sh
docker-compose -f docker-compose.yml up -d
```
I was in the wrong directory.

With this fixing you avoid to enter the `images` directory

Related issue #15998

Signed-off-by: Dario Curreri <dariocurr@gmail.com>

2022-03-10 14:14 UTC, xiaofan-luan commented
/assign @haorenfsa please help on reviewing

2022-03-10 14:21 UTC, haorenfsa commented
/lgtm

2022-03-10 14:22 UTC, haorenfsa commented
/kind improvement

2022-03-10 14:27 UTC, haorenfsa commented
The change looks good. By the way, maybe we should add a script to run these commands together, and test it when we release to avoid this.

2022-03-10 14:29 UTC, haorenfsa commented
/approve

2022-03-10 14:37 UTC, jennyli-z commented
https://github.com/milvus-io/milvus/blob/master/CODE_REVIEW.md#things-to-do-before-review 
![image](https://user-images.githubusercontent.com/93511422/157684203-4e9e9eb8-348d-4ba1-91e6-072c2258b252.png)
@dariocurr  please check the second item in the code review, thanks.

2022-03-10 18:38 UTC, dariocurr commented
I read it. Should I do more?

2022-03-11 01:02 UTC, jennyli-z commented
> I read it. Should I do more? It is just documentation fixing

In order to make the commit history linear for master,  we only accept one commit for one pr, your pr now is mixed with the other pr commit. Please help check and resubmit. Very appreciated!

2022-03-11 01:29 UTC, LoveEachDay requested changes
This file changes do not have any relationship with your pr. You'd better split your commits.
Keep offline installation related changes in this commit.

And the commit message has a typo: `offiline`. Please fix it.

2022-03-11 01:31 UTC, LoveEachDay commented
Seems like you merge the master branch into your pr branch, this is not recommended. Please use `git rebase` instead of `git merge`.

2022-03-11 08:27 UTC, dariocurr commented
I hope everything is fine now.

2022-03-11 10:12 UTC, haorenfsa approved these changes

2022-03-11 10:13 UTC, haorenfsa commented
/lgtm

2022-03-11 10:15 UTC, haorenfsa commented
@xiaofan-luan @LoveEachDay  need maintainer's approve

2022-03-11 10:30 UTC, merged

2022-03-11 10:39 UTC, dariocurr commented
Thank you for your attention and your work