Update compile options and config for embedded Milvus
milvus-io/milvus pull request #16472
Opened 2022-04-13 03:41 UTC by soothing-rain

/kind enhancement

issue: #15711

Signed-off-by: Yuchen Gao <yuchen.gao@zilliz.com>

2022-04-13 04:02 UTC, soothing-rain commented
rerun ut

2022-04-13 04:34 UTC, soothing-rain commented
rerun ut

2022-04-13 04:52 UTC, soothing-rain commented
/assign @XuanYang-cn

2022-04-13 07:19 UTC, XuanYang-cn requested changes

2022-04-13 11:40 UTC, XuanYang-cn commented
/lgtm

2022-04-14 11:57 UTC, congqixia commented
/approve

2022-04-14 11:57 UTC, merged