Add cache of grpc client of ShardLeader in proxy
milvus-io/milvus pull request #17301
Opened 2022-05-31 11:47 UTC by czs007

fix #17207 
Signed-off-by: zhenshan.cao <zhenshan.cao@zilliz.com>

2022-06-01 05:27 UTC, czs007 commented
/hold
wait for all reviewers

2022-06-01 11:21 UTC, XuanYang-cn requested changes

2022-06-01 11:21 UTC, XuanYang-cn commented on internal/proxy/meta_cache.go
> +	//var ret map[string][]nodeInfo
please remove this comment

2022-06-02 04:13 UTC, czs007 commented on internal/proxy/meta_cache.go
> +	//var ret map[string][]nodeInfo
I will delete this in next pr. Okay?

2022-06-02 04:13 UTC, czs007 commented
/unhold

2022-06-02 04:15 UTC, XuanYang-cn commented
/lgtm

2022-06-02 04:16 UTC, merged