Drop segment indexes when drop partition
milvus-io/milvus pull request #19022
Opened 2022-09-05 08:38 UTC by xiaocai2333

Signed-off-by: cai.zhang <cai.zhang@zilliz.com>
issue: #18642

2022-09-06 02:20 UTC, xiaocai2333 commented
rerun ut

2022-09-07 12:32 UTC, xiaocai2333 commented
rerun ut

2022-09-08 03:12 UTC, xiaocai2333 commented
/run-cpu-e2e

2022-09-08 04:07 UTC, xiaocai2333 commented
/run-cpu-e2e

2022-09-08 06:37 UTC, xiaocai2333 commented
/run-cpu-e2e

2022-09-08 09:47 UTC, xiaocai2333 commented
/run-cpu-e2e

2022-09-09 04:04 UTC, czs007 commented on internal/indexcoord/index_coord.go
> +	if req.PartitionID == -1 {
do not use magic number.

2022-09-09 04:11 UTC, czs007 commented on internal/proxy/task.go
> +		PartitionID:  -1,
do  not use magic number

2022-09-15 12:11 UTC, xiaocai2333 commented
/run-cpu-e2e

2022-09-16 08:33 UTC, longjiquan commented
/lgtm

2022-09-19 01:32 UTC, xiaocai2333 commented
/run-cpu-e2e

2022-09-21 03:06 UTC, czs007 commented on internal/rootcoord/broker.go
> +	DropCollectionIndex(ctx context.Context, collID UniqueID, partID UniqueID) error
partIDs []UniqueID

2022-09-21 09:44 UTC, longjiquan requested changes

2022-09-21 09:44 UTC, longjiquan commented on internal/rootcoord/step.go
> +	partID UniqueID
`step` is just a wrapper of broker api. So just keep partIDs same with broker api here.

2022-09-21 09:46 UTC, longjiquan commented on internal/rootcoord/drop_collection_task.go
> +		partID:   -1,
According to the gc logic of indexcoord, passing `-1` will lead indexcoord filter everything, so nothing will be collected. Just passing `nil` here.

2022-09-21 09:47 UTC, longjiquan commented on internal/rootcoord/drop_partition_task.go
> +		partID:   partID,
Use partIDs instead.

2022-09-21 11:23 UTC, longjiquan commented
LGTM

2022-09-22 02:09 UTC, xiaocai2333 commented
/run-cpu-e2e

2022-09-22 02:17 UTC, czs007 commented
/approve

2022-09-22 02:18 UTC, czs007 commented
/lgtm

2022-09-23 01:35 UTC, longjiquan commented
/lgtm

2022-09-23 01:36 UTC, merged