Optimize large memory usage of InsertRecord by using vector instead of unordered_map if InsertRecord used in sealed segment
milvus-io/milvus pull request #19245
Opened 2022-09-16 08:11 UTC by aoiasd

related:https://github.com/milvus-io/milvus/issues/18764 https://github.com/milvus-io/milvus/issues/18845
Signed-off-by: aoiasd <zhicheng.yue@zilliz.com>

2022-09-19 02:08 UTC, aoiasd commented
rerun ut

2022-09-19 02:14 UTC, aoiasd commented
/run-cpu-e2e

2022-09-19 02:35 UTC, aoiasd commented
/run-cpu-e2e

2022-09-19 04:15 UTC, aoiasd commented
/run-cpu-e2e

2022-09-19 08:19 UTC, aoiasd commented
/run-cpu-e2e

2022-09-19 08:42 UTC, aoiasd commented
/run-cpu-e2e

2022-09-19 08:57 UTC, aoiasd commented
/run-cpu-e2e

2022-09-20 03:40 UTC, aoiasd commented
/run-cpu-e2e

2022-09-20 08:07 UTC, aoiasd commented
/run-cpu-e2e

2022-09-20 09:43 UTC, yah01 requested changes

2022-09-20 09:43 UTC, yah01 commented on internal/core/src/segcore/InsertRecord.h
> +    find(const T pk) const {
use `std::binary_search()`

2022-09-20 09:43 UTC, yah01 commented on internal/core/src/segcore/InsertRecord.h
> +        std::vector<SegOffset> res_offsets;
construct this vector with iterator after replace `find` with `std::binary_search()`

2022-09-20 09:43 UTC, yah01 commented on internal/core/src/segcore/InsertRecord.h
> +        for (int offset_id = find(pk_); offset_id < array_.size(); offset_id++) {
same as line 117

2022-09-20 09:50 UTC, jiaoew1991 commented on internal/core/unittest/test_segcore.cpp
> +    std::cout << "insert pks: " << timer.get_step_seconds() << " seconds" << std::endl;
remove it

2022-09-20 09:50 UTC, jiaoew1991 commented on internal/core/unittest/test_segcore.cpp
> +    std::cout << "insert pks: " << timer.get_step_seconds() << " seconds" << std::endl;
the same as L111 L126 etc

2022-09-20 09:50 UTC, jiaoew1991 commented on internal/core/src/segcore/InsertRecord.cpp
> +InsertRecord::InsertRecord(const Schema& schema, int64_t size_per_chunk, bool is_sealed)
sealed is a caller concept，pass a creator or type  is better

2022-09-21 07:44 UTC, aoiasd commented
/run-cpu-e2e

2022-09-22 01:42 UTC, jiaoew1991 commented
/lgtm

2022-09-23 06:42 UTC, jiaoew1991 commented
/lgtm

2022-09-23 09:07 UTC, congqixia commented
/approve

2022-09-23 09:08 UTC, merged