Change compactor policy from loading all binlogs to loading serially …
milvus-io/milvus pull request #19280
Opened 2022-09-19 12:25 UTC by zhagnlu

#19073 
Signed-off-by: zhagnlu <lu.zhang@zilliz.com>

2022-09-21 08:09 UTC, xige-16 commented on internal/datacoord/compaction_trigger.go
> +		if indexInfo.IndexName == diskAnnIndexName {
```	for _, indexInfo := range resp.IndexInfos {
		indexParamsMap := funcutil.KeyValuePair2Map(indexInfo.IndexParams)
		if indexType, ok := indexParamsMap["index_type"]; ok {
			if indexType == indexparamcheck.IndexDISKANN {
				for _, segment := range segments {
					segment.MaxRowNum = int64(Params.DataCoordCfg.DiskSegmentMaxSize)
				}
			}
		}
	}
```

2022-09-21 08:17 UTC, xige-16 commented on internal/datanode/binlog_io.go
>  	upload(ctx context.Context, segID, partID UniqueID, iData []*InsertData, segStats []byte, dData *DeleteData, meta *etcdpb.CollectionMeta) (*segPaths, error)
can removed?

2022-09-22 09:26 UTC, XuanYang-cn requested changes
Compaction costs info is important, please add time elapse logs for each progress, for instance, io-upload-total-elapse, merge-total-elapse, io-download-total-elapse, etc.

2022-09-23 06:37 UTC, congqixia approved these changes
/lgtm

2022-09-23 08:32 UTC, xige-16 commented
/lgtm

2022-09-23 08:43 UTC, czs007 commented on internal/datanode/compactor.go
> +		if fs.GetIsPrimaryKey() && fs.GetFieldID() >= 100 && typeutil.IsPrimaryFieldType(fs.GetDataType()) {
better to use common.StartOfUserFieldID

2022-09-23 08:46 UTC, czs007 commented on internal/datanode/compactor.go
> +		if fs.GetIsPrimaryKey() && fs.GetFieldID() >= 100 && typeutil.IsPrimaryFieldType(fs.GetDataType()) {
you can modify this in next pr

2022-09-24 10:40 UTC, xige-16 commented
/lgtm

2022-09-25 12:12 UTC, merged