Replace segment index file path with index file id within segment index meta
milvus-io/milvus pull request #19866
Opened 2022-10-18 08:17 UTC by jaime0815

isssue #19862 
Signed-off-by: yun.zhang <yun.zhang@zilliz.com>

2022-10-18 08:45 UTC, longjiquan requested changes

2022-10-18 08:45 UTC, longjiquan commented on cmd/tools/migration/meta/210_to_220.go
> +				if len(parts) != 0 {
Should be `len(parts) == 0` here.

2022-10-18 08:45 UTC, longjiquan commented on cmd/tools/migration/meta/210_to_220.go
> +				fileID, err := strconv.ParseInt(parts[len(filePath)-1], 10, 64)
What's the meaning of `fileID` here? The old format of index file path is: `index_files/{index build id}/{version}/{partition id}/{segment id}/{key}`, where key is given by `knowhere`, for example `IVF-1`, `IVF-2`, `indexParams` and etc. So `parts[len(filePath)-1]` won't be parsed to `fileID`.

2022-10-19 02:04 UTC, longjiquan requested changes

2022-10-19 02:04 UTC, longjiquan commented on internal/metastore/model/segment_index.go
> +func CloneIndexFileKeys(src []string) []string {
Maybe `CloneIndexFileKeys` can reuse `common.CloneStringList`.

2022-10-19 02:04 UTC, longjiquan commented on internal/proto/index_coord.proto
> +  repeated string index_file_keys = 11;
I guess you should keep the original wire number `3` instead of `11`.

2022-10-19 02:04 UTC, longjiquan commented on internal/util/metautil/segment_index.go
> +func BuildSegmentIndexFilePathWithPrefix(prefix string, buildID, indexVersion, partID, segID int64, fileKey string) string {
What's the difference between `BuildSegmentIndexFilePathWithPrefix` and `BuildSegmentIndexFilePath`?
Should we also join `common.SegmentIndexPath` when `BuildSegmentIndexFilePathWithPrefix`?

2022-10-19 07:36 UTC, longjiquan commented
/lgtm

2022-10-19 08:54 UTC, czs007 commented on internal/metastore/db/indexcoord/table_catalog.go
> -import (
delete this ? you can delete it in next pr.

2022-10-19 08:54 UTC, czs007 commented
/approve

2022-10-19 08:55 UTC, merged