timestamp decided if the pks were the same
milvus-io/milvus pull request #20166
Opened 2022-10-28 07:26 UTC by smellthemoon

Signed-off-by: lixinguo <xinguo.li@zilliz.com>

2022-10-28 08:13 UTC, smellthemoon commented
rerun ut

2022-10-28 08:14 UTC, smellthemoon commented
/run-cpu-e2e

2022-10-31 06:20 UTC, XuanYang-cn requested changes

2022-10-31 06:20 UTC, XuanYang-cn commented on internal/querynode/result.go
> +				ret.FieldsData = ret.FieldsData[:len(ret.FieldsData)-1]
FieldsData is a list of fields, you need to operate on the separate field in the FieldsData

2022-10-31 06:25 UTC, XuanYang-cn requested changes

2022-10-31 06:25 UTC, XuanYang-cn commented on internal/querynode/result.go
> +				ret.FieldsData = ret.FieldsData[:len(ret.FieldsData)-1]
Please add UT to cover this logic

2022-11-01 07:12 UTC, smellthemoon commented on internal/querynode/result.go
> +				ret.FieldsData = ret.FieldsData[:len(ret.FieldsData)-1]
ok, I will add it.

2022-11-01 07:51 UTC, smellthemoon commented
/run-cpu-e2e

2022-11-01 08:06 UTC, smellthemoon commented
/run-cpu-e2e

2022-11-01 08:07 UTC, smellthemoon commented
/run-cpu-e2e

2022-11-01 08:48 UTC, XuanYang-cn requested changes

2022-11-01 08:48 UTC, XuanYang-cn commented on internal/util/typeutil/schema.go
> +// DeleteFieldData delete fields data from src to dst
Please correct the comment

2022-11-01 08:48 UTC, XuanYang-cn commented on internal/util/typeutil/schema.go
> +func DeleteFieldData(dst []*schemapb.FieldData, src []*schemapb.FieldData, idx int64) {
Please remove `src` and `idx` here, just range over `dst`

2022-11-01 08:48 UTC, XuanYang-cn commented on internal/util/typeutil/schema.go
> +				dstScalar.GetBoolData().Data = dstScalar.GetBoolData().Data[:len(dstScalar.GetBoolData().Data)-1]
This could be panic if there's no data inside, please check the length and prevent panic from happening, just return if length==0.

2022-11-01 08:48 UTC, XuanYang-cn commented on internal/util/typeutil/schema.go
> +				srcToDelete := srcVector.BinaryVector[idx*(dim/8) : (idx+1)*(dim/8)]
`idx` is not needed in here, the last binary vector has a length of  `(dim/8)`, the last float vector has a length of `dim`, just remove the last `dim/8` or `dim` is alright,  `idx` is to retrieve data from `srcs`.

2022-11-01 09:24 UTC, XuanYang-cn commented
/lgtm

2022-11-01 09:49 UTC, jiaoew1991 commented on internal/util/typeutil/schema.go
> +				log.Error("empty field data can't be deleted")
use Info is enough

2022-11-01 09:57 UTC, smellthemoon commented on internal/util/typeutil/schema.go
> +				log.Error("empty field data can't be deleted")
ok

2022-11-01 10:21 UTC, smellthemoon commented
/run-cpu-e2e

2022-11-01 10:36 UTC, smellthemoon commented
/run-cpu-e2e

2022-11-01 10:47 UTC, smellthemoon commented
/run-cpu-e2e

2022-11-01 11:13 UTC, smellthemoon commented
/run-cpu-e2e

2022-11-02 02:12 UTC, smellthemoon commented
/run-cpu-e2e

2022-11-03 09:53 UTC, smellthemoon commented
/run-cpu-e2e

2022-11-04 07:32 UTC, smellthemoon commented
/run-cpu-e2e

2022-11-15 01:57 UTC, smellthemoon commented
/run-cpu-e2e

2022-11-15 01:57 UTC, smellthemoon commented
rerun ut

2022-11-15 16:26 UTC, smellthemoon commented
rerun ut

2022-11-16 01:11 UTC, jiaoew1991 commented on internal/core/src/segcore/SegmentGrowingImpl.cpp
> +            // PanicInfo("timestamp unsupported");
delete it is ok

2022-11-16 06:59 UTC, XuanYang-cn requested changes

2022-11-16 06:59 UTC, XuanYang-cn commented on internal/core/src/segcore/SegmentSealedImpl.cpp
> +    auto field_data = insert_record_.timestamps_.get_chunk_data(0);
Add SystemFieldType::RowID as SegmentGrowingImpl.go and remove the comments.

2022-11-18 05:47 UTC, smellthemoon commented
/run-cpu-e2e

2022-11-18 14:23 UTC, smellthemoon commented
rerun ut

2022-11-21 02:20 UTC, XuanYang-cn commented
/lgtm

2022-11-21 02:27 UTC, congqixia approved these changes
/kind enhancement
/approve

2022-11-21 02:55 UTC, merged