Avoid delete segment which has been loaded
milvus-io/milvus pull request #20530
Opened 2022-11-11 11:40 UTC by xige-16

/kind improvement
Signed-off-by: xige-16 <xi.ge@zilliz.com>

2022-11-11 11:55 UTC, yah01 requested changes

2022-11-11 11:55 UTC, yah01 commented on internal/querynode/segment_loader.go
> +		segmentGC(false)
need to handle block list of load segments task

2022-11-11 11:57 UTC, yah01 commented
/lgtm

2022-11-11 12:05 UTC, congqixia reviewed
If `LoadSegment` returns error, the `watchDeltaChannel` and `FromDmLoadDelete` operations will be skipped. This may cause integrity problem.

2022-11-11 12:10 UTC, yah01 commented on internal/querynode/segment_loader.go
>  		return err
can't return error here

2022-11-11 12:20 UTC, yah01 commented
/hold

2022-11-11 13:33 UTC, yah01 commented on internal/querynode/segment_loader.go
> +		return loadDoneSegmentIDs, err
need to add the loaded segment into meta

2022-11-11 13:35 UTC, yah01 commented
/unhold

2022-11-12 12:51 UTC, xiaofan-luan commented
/hold

2022-11-15 03:23 UTC, xiaofan-luan commented
/lgtm 
/approve

2022-11-15 03:25 UTC, merged