add search option to ignore ignore segment
milvus-io/milvus pull request #21994
Opened 2023-02-06 04:02 UTC by aoiasd

https://github.com/milvus-io/milvus/issues/21836

2023-02-06 09:32 UTC, aoiasd commented
/run-cpu-e2e

2023-02-06 10:22 UTC, aoiasd commented
rerun ut

2023-02-15 08:41 UTC, congqixia requested changes

2023-02-15 08:41 UTC, congqixia commented on internal/querynode/shard_cluster.go
> +func getSearchWithStreamingFunc(searchCtx context.Context, req *querypb.SearchRequest, node *QueryNode, qs *queryShard, nodeID int64, streamingResults **internalpb.SearchResults) withStreaming {
Please do not use `**internalpb.SearchResults`. We could modify `WithStreaming` signature to fix this problem

2023-02-18 00:04 UTC, xiaofan-luan commented
looks good!
we should bring this in for 2.2.4

2023-02-21 06:12 UTC, aoiasd commented
rerun ut

2023-02-21 11:25 UTC, aoiasd commented
/run-cpu-e2e

2023-02-21 11:28 UTC, aoiasd commented
/run-cpu-e2e

2023-02-22 02:43 UTC, aoiasd commented
/run-cpu-e2e

2023-02-22 09:30 UTC, congqixia approved these changes
/lgtm
/kind enhancement

2023-02-22 09:31 UTC, merged

2023-02-22 10:46 UTC, xiaofan-luan commented
Good job!
Hopefully we can get this feature work in 2.2.4!