trigger more logs when fail
milvus-io/milvus pull request #22477
Opened 2023-02-28 10:21 UTC by XuanYang-cn

/hold

2023-03-01 09:38 UTC, XuanYang-cn commented
/run-cpu-e2e

2023-03-02 04:02 UTC, zhuwenxing requested changes

2023-03-02 04:02 UTC, zhuwenxing commented on tests/python_client/testcases/test_search.py
> +            print(f"pagination ids: {res[0].ids[offset:]}")
using log.info() is better

2023-03-02 07:35 UTC, XuanYang-cn commented
/run-cpu-e2e

2023-03-02 08:32 UTC, XuanYang-cn commented
/run-cpu-e2e

2023-03-02 10:09 UTC, XuanYang-cn commented
/run-cpu-e2e

2023-03-02 10:46 UTC, XuanYang-cn commented
/run-cpu-e2e

2023-03-03 02:28 UTC, XuanYang-cn commented
/run-cpu-e2e

2023-03-06 02:59 UTC, XuanYang-cn commented
/run-cpu-e2e

2023-03-07 07:34 UTC, XuanYang-cn commented
/unhold

2023-03-07 07:34 UTC, XuanYang-cn commented
/assign @NicoYuan1986

2023-03-08 03:02 UTC, jiaoew1991 approved these changes
/lgtm

2023-03-08 03:03 UTC, merged