Replace ErrorList with multiErrors
milvus-io/milvus pull request #22532
Opened 2023-03-02 09:35 UTC by congqixia

Related to #22519

/kind improvement

Signed-off-by: Congqi Xia <congqi.xia@zilliz.com>

2023-03-02 09:39 UTC, yah01 requested changes

2023-03-02 09:39 UTC, yah01 commented on internal/storage/local_chunk_manager.go
> +	//var el errorutil.ErrorList
why not just remove it

2023-03-02 09:43 UTC, congqixia commented on internal/storage/local_chunk_manager.go
> +	//var el errorutil.ErrorList
fixed

2023-03-03 06:59 UTC, yah01 commented
/lgtm

2023-03-03 06:59 UTC, merged