Fix upsert msgid
milvus-io/milvus pull request #22839
Opened 2023-03-20 01:00 UTC by smellthemoon

#22563 
/kind bug

2023-03-20 09:59 UTC, smellthemoon commented
/run-cpu-e2e

2023-03-21 01:30 UTC, jiaoew1991 commented on internal/proxy/task_delete.go
> +				return err
error should be wrapped

2023-03-21 01:30 UTC, jiaoew1991 commented on internal/proxy/task_delete.go
> +					commonpbutil.WithMsgID(msgid),
add a UT for this case?

2023-03-21 02:51 UTC, yah01 requested changes

2023-03-21 02:51 UTC, yah01 commented on internal/util/merr/errors.go
> +	ErrIDAllocatorFailed = newMilvusError("IDAllocatorFailed", 1300, false)
We don't need to add an error here, as failed to allocate a ID/timestamp is not a leaf error, the cause should be returned by the allocator itself

2023-03-21 02:51 UTC, yah01 commented on internal/proxy/task_upsert.go
> +				return merr.WrapErrIDAllocatorFailed("Fail to alloc msgid when deleteExecute in upsert")
The original error lost, just `errors.Wrap(err, "failed to allocate MsgID for delete of upsert")`

2023-03-21 02:51 UTC, yah01 commented on internal/proxy/task_delete.go
> +				return merr.WrapErrIDAllocatorFailed("Fail to alloc msgid when Execute in delete")
The original error lost, just `errors.Wrap(err, "failed to allocate MsgID for delete")`

2023-03-21 04:53 UTC, jiaoew1991 approved these changes
/lgtm

2023-03-21 06:06 UTC, merged