Add DescribeAlias and ListAliases interfaces
milvus-io/milvus pull request #22881
Opened 2023-03-21 05:59 UTC by wayblink

2023-03-22 05:50 UTC, wayblink commented
/run-cpu-e2e

2023-03-22 05:50 UTC, wayblink commented
/run-gpu-e2e

2023-03-22 10:44 UTC, wayblink commented
rerun ut

2023-03-23 07:34 UTC, wayblink commented
/run-cpu-e2e

2023-03-23 08:23 UTC, wayblink commented
/run-gpu-e2e

2023-03-23 12:31 UTC, xiaofan-luan commented on internal/rootcoord/root_coord.go
> +			Status: merr.Status(err),
Error code

2023-03-23 12:31 UTC, xiaofan-luan commented on internal/rootcoord/root_coord.go
> +		return &milvuspb.ListAliasesResponse{
error code

2023-03-23 12:31 UTC, xiaofan-luan commented on internal/types/types.go
> +	// ListAliases query RootCoord to show all alias for the db
should we support alias for single collection?

2023-03-23 12:31 UTC, xiaofan-luan commented on internal/types/types.go
> +	ListAliases(ctx context.Context, req *milvuspb.ListAliasRequest) (*milvuspb.ListAliasesResponse, error)
Alias need to be cotest with collection rename feature to make sure they can work together

2023-03-23 12:40 UTC, xiaofan-luan commented on internal/distributed/proxy/service.go
> +func (s *Server) ListAliases(ctx context.Context, request *milvuspb.ListAliasRequest) (*milvuspb.ListAliasesResponse, error) {
ListAlias should support list alias on one collection?

2023-03-23 12:50 UTC, xiaofan-luan commented on internal/proxy/impl.go
> +			Status: unhealthyStatus(),
need to return with error code

2023-03-23 12:50 UTC, xiaofan-luan commented on internal/proxy/impl.go
> +				ErrorCode: commonpb.ErrorCode_UnexpectedError,
need to return with error code here

2023-03-24 07:22 UTC, wayblink commented
rerun ut

2023-03-24 07:29 UTC, wayblink commented
/run-gpu-e2e

2023-03-24 11:59 UTC, wayblink commented
rerun ut

2023-03-24 11:59 UTC, wayblink commented
/run-gpu-e2e

2023-03-25 16:26 UTC, wayblink commented
/run-cpu-e2e

2023-03-25 16:26 UTC, wayblink commented
/run-gpu-e2e

2023-03-29 02:47 UTC, wayblink commented
/run-cpu-e2e

2023-03-29 06:03 UTC, wayblink commented
rerun ut

2023-03-29 06:03 UTC, wayblink commented
/run-cpu-e2e

2023-03-29 14:35 UTC, wayblink commented
rerun ut

2023-04-01 07:41 UTC, wayblink commented
rerun ut

2023-04-24 02:05 UTC, wayblink commented
/run-cpu-e2e

2023-05-05 02:14 UTC, wayblink commented
rerun ut

2023-05-05 09:28 UTC, wayblink commented
rerun ut

2023-05-09 02:49 UTC, longjiquan requested changes

2023-05-09 02:49 UTC, longjiquan commented on internal/rootcoord/meta_table.go
> +		return "", merr.WrapErrAliasNotFound(alias)
Please add ut for this case.

2023-05-09 02:49 UTC, longjiquan commented on internal/rootcoord/meta_table.go
> +	mt.ddLock.Lock()
Use `RLock` instead.

2023-05-09 02:49 UTC, longjiquan commented on internal/rootcoord/meta_table.go
> +		return "", merr.WrapErrCollectionIDOfAliasNotFound(collectionID)
Please add ut for this case.

2023-05-09 02:49 UTC, longjiquan commented on internal/rootcoord/meta_table.go
> +	return collectionMeta.Name, nil
Please check if the collection was availiable.

2023-05-09 02:49 UTC, longjiquan commented on internal/rootcoord/meta_table.go
> +	mt.ddLock.Lock()
Use `RLock` instead.

2023-05-09 02:49 UTC, longjiquan commented on internal/proxy/impl.go
> +	dat := &DescribeAliasTask{
How about using `return node.rootCoord.DescribeAlias` directly? Anyway, these two apis will be scheduled by the rootcoord's queue.

2023-05-09 02:49 UTC, longjiquan commented on internal/proxy/task.go
> +type DescribeAliasTask struct {
Please split these two structs into two files if these tasks are really required.

2023-05-09 02:49 UTC, longjiquan commented on internal/rootcoord/meta_table.go
> +	}
Please check if the collection was availiable.

2023-05-09 02:49 UTC, longjiquan commented on internal/rootcoord/root_coord.go
> +	if code, ok := c.checkHealthy(); !ok {
Please add ut for this case. You can just look at how we test the `CreateCollection`, and you'll know it's very easy to do this.

2023-05-09 02:49 UTC, longjiquan commented on internal/rootcoord/root_coord.go
> +	collectionName, err := c.meta.DescribeAlias(ctx, in.GetAlias(), 0)
I prefer to letting these two requests scheduled by the rootcoord instead of proxy.

2023-05-11 08:36 UTC, wayblink commented
rerun ut

2023-07-05 04:40 UTC, wayblink commented
/run-gpu-e2e

2023-07-05 06:45 UTC, wayblink commented
/run-gpu-e2e

2023-07-06 03:35 UTC, wayblink commented
/run-gpu-e2e

2023-07-06 10:17 UTC, wayblink commented
/run-gpu-e2e

2023-07-25 11:25 UTC, wayblink commented
rerun ut

2023-07-28 07:59 UTC, wayblink commented
/assign @xiaofan-luan

2023-08-09 09:00 UTC, wayblink commented
/run-cpu-e2e

2023-08-09 12:20 UTC, wayblink commented
/run-cpu-e2e

2023-08-09 12:39 UTC, wayblink commented
rerun ut

2023-08-10 09:00 UTC, wayblink commented
/run-cpu-e2e

2023-09-19 23:06 UTC, closed without merging