Use merr in proxy
milvus-io/milvus pull request #22904
Opened 2023-03-21 11:12 UTC by smellthemoon

Signed-off-by: lixinguo [xinguo.li@zilliz.com](mailto:xinguo.li@zilliz.com)
/kind improvement

2023-03-22 04:47 UTC, smellthemoon commented
rerun ut

2023-03-22 06:40 UTC, smellthemoon commented
rerun ut

2023-03-23 10:21 UTC, yah01 requested changes

2023-03-23 10:21 UTC, yah01 commented on internal/proxy/authentication_interceptor.go
> +				return nil, merr.WrapErrIoFailed("metadata", "auth check failure, please check username and password are correct")
It should be ErrParameterInvalid

2023-03-23 10:21 UTC, yah01 commented on internal/util/merr/errors.go
> +	ErrMemoryNotSufficient = newMilvusError("memory not sufficient to load", 1300, false)
Redundancy of ErrServiceMemoryLimitExceeded

2023-03-24 05:43 UTC, smellthemoon commented on internal/proxy/impl.go
> +			Status: merr.Status(err),
ok, will keep the error not change until qn has processed.

2023-03-24 07:26 UTC, jiaoew1991 approved these changes
/lgtm

2023-03-24 07:27 UTC, merged