Add FlushAll [cherry-pick#22942]
milvus-io/milvus pull request #22970
Opened 2023-03-24 04:02 UTC by bigsheeper

issues: https://github.com/milvus-io/milvus/issues/22921

2023-03-27 03:07 UTC, longjiquan requested changes

2023-03-27 03:07 UTC, longjiquan commented on internal/proxy/impl.go
> +		return nil, err
Ditto, same above.

2023-03-27 03:07 UTC, longjiquan commented on internal/proxy/impl.go
> +		log.Warn("FlushAll failed", zap.String("err", flushRsp.GetStatus().GetReason()))
Ditto, same above.

2023-03-27 03:07 UTC, longjiquan commented on internal/proxy/impl.go
> +		log.Warn("FlushAll failed", zap.Error(err))
Use `info` here.

2023-03-27 03:07 UTC, longjiquan commented on internal/proxy/impl.go
> +		log.Warn("GetFlushAllState failed", zap.Error(err))
Ditto, same above.

2023-03-27 03:54 UTC, bigsheeper commented on internal/datacoord/services.go
> +		log.Warn("failed to ShowCollections", zap.Error(err))
Why use Info here？
`ShowCollections ` is better to search log when debugging, any strong reason to use `show collections`?

2023-03-27 03:56 UTC, bigsheeper commented on internal/datacoord/services.go
> +			channelCP := s.meta.GetChannelCheckpoint(channel)
It's ok, just wait for next round to GetFlushAllState.

2023-03-29 02:39 UTC, jaime0815 commented on internal/datacoord/services.go
> +			resp.Status.Reason = err.Error()
should set  error code of describe the response to this status

2023-03-29 02:40 UTC, jaime0815 commented on internal/datacoord/services.go
> +		resp.Status.Reason = err.Error()
should set error code of describe the response to this status

2023-03-29 03:31 UTC, bigsheeper commented
/run-cpu-e2e

2023-03-30 03:26 UTC, czs007 commented
/approve

2023-03-30 03:28 UTC, merged