Migrate the ability to upload and download binlog to cpp
milvus-io/milvus pull request #22984
Opened 2023-03-24 09:31 UTC by xige-16

fix issue: https://github.com/milvus-io/milvus/issues/21266
/kind bug

pick pr to 2.2.0 branch: https://github.com/milvus-io/milvus/pull/22382
Signed-off-by: xige-16 <xi.ge@zilliz.com>

2023-06-12 02:17 UTC, yah01 requested changes

2023-06-12 02:17 UTC, yah01 commented on internal/core/src/mmap/Column.h
> +// Licensed to the LF AI & Data foundation under one
keep the files structure same with 2.2.0 branch, also the Column type is not for mmap only

2023-06-13 06:43 UTC, jiaoew1991 commented on internal/core/src/common/type_c.h
>  typedef struct CLoadDeletedRecordInfo {
This struct should also be deleted, right?

2023-06-13 06:43 UTC, jiaoew1991 commented on internal/core/src/index/StringIndexMarisa.cpp
> +            assert(valid_str_id(str_id));
Add some error message here?

2023-06-15 06:33 UTC, xige-16 commented
rerun ut

2023-06-21 10:34 UTC, jiaoew1991 commented
/lgtm 
/approve

2023-06-21 10:36 UTC, czs007 commented
/hold

2023-06-25 02:48 UTC, czs007 commented on internal/core/src/index/ScalarIndexSort-inl.h
> +    if (file_manager != nullptr) {
better to add a AssertInfo

2023-06-25 03:05 UTC, czs007 commented on internal/core/src/index/StringIndexMarisa.cpp
>      if (built_) {
better to keep same with other ScalarIndex which is just return

2023-06-25 03:07 UTC, czs007 commented on internal/core/src/index/Utils.cpp
> +    if (index_datas.find(INDEX_FILE_SLICE_META) != index_datas.end()) {
better to assert index_datas have INDEX_FILE_SLICE_META

2023-06-25 03:22 UTC, czs007 commented on internal/core/src/indexbuilder/index_c.cpp
>  CreateIndex(enum CDataType dtype,
you can delete this.

2023-06-25 06:37 UTC, czs007 commented
/unhold

2023-06-25 06:38 UTC, merged