Fix LoadSegment req don't fill in collection id
milvus-io/milvus pull request #23136
Opened 2023-03-30 03:13 UTC by smellthemoon

Signed-off-by: lixinguo [xinguo.li@zilliz.com](mailto:xinguo.li@zilliz.com)
#23113

2023-03-30 03:48 UTC, jiaoew1991 commented
/lgtm 
/approve

2023-03-30 03:54 UTC, yah01 commented on internal/querynodev2/services.go
> +			CollectionID: req.CollectionID,
prefer `req.GetCollectionID()`

2023-03-30 04:10 UTC, yah01 requested changes

2023-03-30 04:10 UTC, yah01 commented on internal/querynodev2/services.go
> +			CollectionID: action.GetInfo().GetCollectionID(),
For release action, the `Info` is `nil`

2023-03-30 04:14 UTC, yah01 commented
/lgtm

2023-03-31 01:58 UTC, jiaoew1991 commented
/lgtm
/approve

2023-03-31 01:59 UTC, congqixia approved these changes
/lgtm

2023-03-31 02:54 UTC, yah01 commented
is there the same problem with 2.2.0 branch? @smellthemoon

2023-03-31 03:18 UTC, smellthemoon commented
> is there the same problem with 2.2.0 branch? @smellthemoon

No, this bug was introduced by qnv2.

2023-03-31 03:28 UTC, merged