Check if loaded before delegator search/query
milvus-io/milvus pull request #23162
Opened 2023-03-31 07:37 UTC by bigsheeper

issue: #23141

2023-03-31 09:38 UTC, bigsheeper commented
rerun ut

2023-03-31 10:53 UTC, yah01 requested changes

2023-03-31 10:53 UTC, yah01 commented on internal/querynodev2/delegator/delegator.go
> +		return nil, fmt.Errorf("partitions not loaded into memory, collectionID=%d, partitionIDs=%s",
use `merr.WrapPartitionNotLoaded`

2023-03-31 10:53 UTC, yah01 commented on internal/querynodev2/delegator/delegator.go
> +		return nil, fmt.Errorf("partitions not loaded into memory, collectionID=%d, partitionIDs=%s",
Same as line 210

2023-04-03 02:22 UTC, bigsheeper commented
/run-cpu-e2e

2023-04-03 06:25 UTC, congqixia approved these changes
/lgtm

2023-04-03 06:26 UTC, merged