fix pull target
milvus-io/milvus pull request #23325
Opened 2023-04-10 09:20 UTC by weiliu1031

Signed-off-by: Wei Liu <wei.liu@zilliz.com>
issue: #23231

2023-04-11 02:47 UTC, weiliu1031 commented
/hold

2023-04-12 04:02 UTC, weiliu1031 commented
/unhold

2023-04-12 10:23 UTC, yah01 requested changes

2023-04-12 10:23 UTC, yah01 commented on internal/querycoordv2/meta/coordinator_broker.go
> +		err = errors.New(recoveryInfo.GetStatus().GetReason())
-> `err := merr.Error(recoveryInfo.GetStatus())`

2023-04-12 10:23 UTC, yah01 commented on internal/querycoordv2/meta/target_manager.go
> +	if partitions != nil {
it may be better to use `len(partitions) > 0`

2023-04-12 10:23 UTC, yah01 commented on internal/querycoordv2/meta/target_manager.go
> +		zap.Int64s("PartitionIDs", partitionIDs))
-> `partitionIDs`

2023-04-12 10:49 UTC, weiliu1031 commented on internal/querycoordv2/meta/coordinator_broker.go
> +		err = errors.New(recoveryInfo.GetStatus().GetReason())
branch 2.2 doesn't support merr

2023-04-13 02:16 UTC, weiliu1031 commented
/run-cpu-e2e

2023-04-17 02:58 UTC, jiaoew1991 commented
/lgtm

2023-04-18 02:27 UTC, congqixia commented
/approve

2023-04-18 02:28 UTC, congqixia commented
/kind enhancement

2023-04-18 02:28 UTC, merged