Change some configurations, include change the defaultChannelNum to 16
milvus-io/milvus pull request #23617
Opened 2023-04-23 06:33 UTC by smellthemoon

Signed-off-by: lixinguo [xinguo.li@zilliz.com](mailto:xinguo.li@zilliz.com)
#23475

2023-04-23 07:30 UTC, jiaoew1991 commented on configs/milvus.yaml
> +  rocksmqPageSize: 67108864 # 64 MB, 64 * 1024 * 1024 bytes, The size of each page of messages in rocksmq
Need to update the corresponding 'Doc' field in service_params.go.

2023-04-23 10:40 UTC, smellthemoon commented
/run-cpu-e2e

2023-04-23 14:01 UTC, smellthemoon commented
/run-cpu-e2e

2023-04-24 02:32 UTC, smellthemoon commented
/run-cpu-e2e

2023-04-24 07:49 UTC, smellthemoon commented
/run-cpu-e2e

2023-04-25 02:30 UTC, congqixia requested changes
Max Channel Number can be scaled in. What's the process of scaling in pre-configured channel names?

2023-04-25 02:30 UTC, congqixia commented on internal/rootcoord/timeticksync.go
> +	}
`len(chanMap)` cannot be used as channel number. Length is actually collection number.

2023-04-25 02:30 UTC, congqixia commented on internal/rootcoord/timeticksync.go
> +	}
Also, can we use the exceeded channel numbers here?

2023-04-25 06:46 UTC, smellthemoon commented
/rerun ut

2023-04-26 10:52 UTC, congqixia requested changes

2023-04-26 10:52 UTC, congqixia commented on internal/rootcoord/util.go
> +	return ret
case 
chanMap = map[int64]channels {
1: {"dml_1", "dml_2"},
2: {"dml_2", "dml_3"},
}
needed number shall be 3, not 4

2023-04-27 01:56 UTC, congqixia commented on pkg/util/paramtable/service_param.go
> +		Doc:          "64 MB, 64 * 1024 * 1024 bytes, The size of each page of messages in rocksmq",
We shall not change the version for changing the default value

2023-04-27 01:56 UTC, congqixia commented on pkg/util/paramtable/service_param.go
> +		Doc:          "3 days, 3 * 24 * 60 minutes, The retention time of the message in rocksmq.",
ditto

2023-04-27 01:57 UTC, congqixia reviewed
overall lgtm
could you please fix the version update issue?

2023-04-27 06:26 UTC, congqixia approved these changes
/lgtm

2023-04-27 06:26 UTC, merged

2023-04-29 06:01 UTC, xiaofan-luan commented on internal/rootcoord/util.go
> +	ret := chanNames.Len()
what if chanMap is 
prefix-1, prefix-8, prefix-10?
I think we need to create at least 10 channels on that case

2023-04-29 06:03 UTC, xiaofan-luan commented on internal/rootcoord/dml_channels.go
> +		chanNum = int64(len(params.TopicNames.GetAsStrings())) + chanNumDefault
don't really understand it's meaning