Fix creating partition is not atomic
milvus-io/milvus pull request #23823
Opened 2023-04-30 07:03 UTC by bigsheeper

issues: https://github.com/milvus-io/milvus/issues/23436

/kind bug

2023-05-04 02:12 UTC, longjiquan requested changes
Please also add recovery logic for creating partition.

2023-05-04 09:09 UTC, longjiquan requested changes

2023-05-04 09:09 UTC, longjiquan commented on internal/rootcoord/garbage_collector.go
> +	redoTask.AddAsyncStep(&removePartitionMetaStep{
`removePartitionMetaStep` should be executed after `releasePartition`.

2023-05-04 11:50 UTC, longjiquan commented
/lgtm

2023-05-05 01:59 UTC, bigsheeper commented
rerun ut

2023-05-08 02:08 UTC, czs007 commented
/approve

2023-05-08 02:14 UTC, czs007 commented
/lgtm

2023-05-08 02:18 UTC, merged