Support partition key
milvus-io/milvus pull request #23994
Opened 2023-05-09 13:47 UTC by xige-16

issue: https://github.com/milvus-io/milvus/issues/23553

Signed-off-by: xige-16 <xi.ge@zilliz.com>

2023-05-12 06:14 UTC, xige-16 commented
rerun UT

2023-05-12 07:10 UTC, xige-16 commented
rerun ut

2023-05-13 11:02 UTC, xiaofan-luan commented on internal/proxy/task_delete.go
> +	partitionKeyMode, err := isPartitionKeyMode(ctx, dt.CollectionName)
how did delete handle partition ID?

2023-05-15 00:47 UTC, xige-16 commented
rerun ut

2023-05-15 03:44 UTC, longjiquan requested changes

2023-05-15 03:58 UTC, xige-16 commented on internal/proxy/task_delete.go
> +	partitionKeyMode, err := isPartitionKeyMode(ctx, dt.CollectionName)
milvus only support deleting on primary field

2023-05-15 06:02 UTC, xige-16 commented on internal/proxy/expr_checker_test.go
> +		exprStr := "partition_key_field in [7, 8] && partition_key_field not in [10, 20]"
done

2023-05-15 06:02 UTC, xige-16 commented on internal/proxy/task.go
> +	partitionKeyMode, err := isPartitionKeyMode(ctx, spt.CollectionName)
done

2023-05-15 06:02 UTC, xige-16 commented on internal/proxy/task.go
> +		return fmt.Errorf("partitions should be specified only on partition key field, field name = %s", cct.schema.Fields[idx].Name)
done

2023-05-15 13:29 UTC, xiaofan-luan commented
/lgtm
/approve

2023-05-15 13:31 UTC, merged