Check metric type before search
milvus-io/milvus pull request #24652
Opened 2023-06-05 03:45 UTC by bigsheeper

issue: https://github.com/milvus-io/milvus/issues/24533

/kind enhancement

2023-06-05 03:45 UTC, bigsheeper commented
test:

![image](https://github.com/milvus-io/milvus/assets/42060877/4e97e68d-d673-4a77-917d-698c637703c7)

2023-06-05 06:20 UTC, yah01 requested changes

2023-06-05 06:20 UTC, yah01 commented on internal/querynodev2/services.go
> +		failRet.Status.Reason = merr.WrapErrCollectionNotFound(req.GetReq().GetCollectionID()).Error()
failRet.Status = merr.Status(merr.WrapErrXxx(...))

2023-06-05 06:20 UTC, yah01 commented on internal/querynodev2/services.go
> +			failRet.Status.Reason = merr.WrapErrParameterInvalid(collection.GetMetricType(), req.GetReq().GetMetricType(),
Same as line 763

2023-06-05 06:31 UTC, bigsheeper commented
also related: https://github.com/milvus-io/milvus/issues/24555

2023-06-05 11:41 UTC, czs007 commented
/approve
/lgtm

2023-06-07 07:56 UTC, czs007 commented
/approve
/lgtm

2023-06-07 07:58 UTC, merged