Add default retrieve limit
milvus-io/milvus pull request #24782
Opened 2023-06-09 05:35 UTC by xige-16

issue: #24435 

/kind bug
Signed-off-by: xige-16 <xi.ge@zilliz.com>

2023-07-07 10:40 UTC, xige-16 commented
/hold

2023-07-18 07:06 UTC, czs007 commented on internal/core/src/segcore/SegmentInterface.cpp
> +                                   int64_t limit_rows,
There is no need to specify a limit for the number of rows.

2023-08-03 12:04 UTC, longjiquan requested changes

2023-08-03 12:04 UTC, longjiquan commented on internal/querynodev2/segments/segment_loader.go
> +			err = segment.UpdateFieldRawDataSize(numRows, fieldInfo.FieldBinlog)
OK, I got it. When the field was indexed, we use binlog size to set the average size.

2023-08-04 02:00 UTC, longjiquan commented on internal/core/src/segcore/SegmentInterface.h
> +    get_field_avg_size(FieldId field_id) = 0;
Also, this function should be marked as const.

2023-08-07 02:32 UTC, xige-16 commented on internal/core/src/segcore/SegmentInterface.h
> +             int64_t limit_size = DEFAULT_MAX_OUTPUT_SIZE) = 0;
> Default parameter value is not suggested for virtual function.

Why？

2023-08-07 02:39 UTC, xige-16 commented on internal/core/src/segcore/SegmentInterface.cpp
> +        throw std::runtime_error("unsupported system field id");
> Add ut for this case.

see internal/core/unittest/test_retrieve.cpp：271

2023-08-07 06:24 UTC, longjiquan requested changes

2023-08-07 06:24 UTC, longjiquan commented on internal/core/src/segcore/segment_c.h
> +updateFieldRawDataSize(CSegmentInterface c_segment,
Capitalize the first letter to keep same coding style with other apis.

2023-08-09 06:34 UTC, czs007 commented
/approve

2023-08-09 06:35 UTC, longjiquan commented
/lgtm

2023-08-10 06:08 UTC, czs007 commented
/unhold

2023-08-10 06:11 UTC, merged