Fix delete record may be re-applied
milvus-io/milvus pull request #24858
Opened 2023-06-13 08:03 UTC by yah01

/kind bug
related #24234 
- Also fixes the load stats never stops
- Also fixes GetDeletedCount() returns the number of rows

2023-06-13 10:49 UTC, yah01 commented
rerun ut

2023-06-14 03:36 UTC, yah01 commented
rerun ut

2023-06-15 01:59 UTC, yah01 commented
rerun ut

2023-06-16 09:18 UTC, yah01 commented
rerun ut

2023-06-19 02:32 UTC, congqixia requested changes

2023-06-19 02:32 UTC, congqixia commented on internal/querynode/load_segment_task.go
> +		if err != nil {
This error will never be not nil since err in for loop is shaded

2023-06-28 07:59 UTC, yah01 commented
rerun ut

2023-06-28 08:59 UTC, yah01 commented
rerun ut

2023-06-28 10:07 UTC, yah01 commented
rerun ut

2023-07-03 06:49 UTC, congqixia commented on internal/querynode/segment.go
> +		return timestamps[i] >= s.flushedDeletedTimestamp+1
why not use 
```
return timestamps[i] > s.flushedDeletedTimestamp
```

2023-07-03 06:49 UTC, congqixia approved these changes
/lgtm

2023-07-03 07:04 UTC, merged