Fix collection and channel not match
milvus-io/milvus pull request #25859
Opened 2023-07-24 03:47 UTC by smellthemoon

Signed-off-by: lixinguo [xinguo.li@zilliz.com](mailto:xinguo.li@zilliz.com)
/kind bug
#25662

2023-07-24 04:50 UTC, jaime0815 commented on internal/proxy/meta_cache.go
> +	GetCollectionInfo(ctx context.Context, database, collectionName string, collectionID int64) (*collectionInfo, error)
we'd better add new method to support get collection by id

2023-07-24 04:50 UTC, jaime0815 commented on internal/proxy/meta_cache.go
> +	GetShards(ctx context.Context, withCache bool, database, collectionName string, collectionID int64) (map[string][]nodeInfo, error)
we'd better add a new method to support get shards by id

2023-07-25 02:33 UTC, smellthemoon commented
/run-cpu-e2e

2023-07-25 04:08 UTC, yah01 requested changes

2023-07-25 04:08 UTC, yah01 commented on internal/proxy/meta_cache.go
> +			coll, err = m.describeCollection(ctx, database, collectionName, 0)
Divide this method to two versions, one looks up by collection name, and one looks up by collection ID

2023-07-25 04:08 UTC, yah01 commented on internal/proxy/meta_cache.go
> +func (m *MetaCache) GetShards(ctx context.Context, withCache bool, database, collectionName string, collectionID int64) (map[string][]nodeInfo, error) {
same as `GetCollectionInfo`

2023-07-28 10:27 UTC, smellthemoon commented
/run-cpu-e2e

2023-07-28 10:28 UTC, smellthemoon commented
rerun ut

2023-07-31 02:39 UTC, smellthemoon commented
rerun ut

2023-07-31 06:58 UTC, jiaoew1991 commented on internal/proxy/meta_cache.go
> +	log.Ctx(ctx).With(
Do you need to write `log := log.Ctx(ctx)` like this? 🤔

2023-07-31 08:44 UTC, smellthemoon commented
/run-cpu-e2e

2023-07-31 12:31 UTC, smellthemoon commented
/run-cpu-e2e

2023-07-31 15:33 UTC, smellthemoon commented
/run-cpu-e2e

2023-08-01 02:59 UTC, smellthemoon commented
/run-cpu-e2e

2023-08-01 07:06 UTC, smellthemoon commented
/run-cpu-e2e

2023-08-01 09:32 UTC, jiaoew1991 commented
/lgtm
/approve

2023-08-01 09:33 UTC, merged