Reduce MQ buffer length and flowgraph wait queue length to 16
milvus-io/milvus pull request #26179
Opened 2023-08-07 10:19 UTC by congqixia

See also #26177
/kind improvement

2023-08-08 08:33 UTC, XuanYang-cn requested changes

2023-08-08 08:33 UTC, XuanYang-cn commented on pkg/util/paramtable/component_param.go
> +		DefaultValue: "16",
it's 1024 in milvus.yaml, the same as pipeline of querynode, better to unify all DefaultValue to 16??
![image](https://github.com/milvus-io/milvus/assets/51370125/bc226516-d055-4353-b089-426dba8d6170)
![image](https://github.com/milvus-io/milvus/assets/51370125/1a52ed4f-82df-4866-a62d-0ef0b67802e4)

2023-08-08 08:52 UTC, jiaoew1991 commented on pkg/mq/msgstream/mq_factory.go
> +		PulsarBufSize:    serviceParam.MQCfg.MQBufSize.GetAsInt64(),
rename PulsarBufSize  to MQBufSize?

2023-08-08 08:52 UTC, jiaoew1991 commented on pkg/mq/msgstream/mq_factory.go
> +		ReceiveBufSize:    config.MQCfg.ReceiveBufSize.GetAsInt64(),
Does Kafka need the MQBufSize parameter?

2023-08-09 02:03 UTC, jiaoew1991 commented
/lgtm

2023-08-09 02:05 UTC, merged