Fast GC compacted dropped segment
milvus-io/milvus pull request #26207
Opened 2023-08-08 07:07 UTC by czs007

#26205

2023-08-08 07:07 UTC, czs007 commented
/hold

2023-08-08 07:37 UTC, XuanYang-cn requested changes

2023-08-08 11:45 UTC, xiaofan-luan commented on internal/datacoord/garbage_collector.go
> +			log.Info("trigger fast GC segment")
should be logged with more information

2023-08-09 05:47 UTC, xiaofan-luan commented
/lgtm
/approve

2023-08-09 10:15 UTC, xiaofan-luan commented
/lgtm
/approve

2023-08-09 10:20 UTC, czs007 commented on internal/datacoord/garbage_collector_test.go
> +		D: dropped, not indexed, should not be GCed, since E is not GCed
since E is not indexed

2023-08-09 11:35 UTC, czs007 commented
/unhold

2023-08-09 11:39 UTC, merged