avoid concurrent sub/unsub on same channel
milvus-io/milvus pull request #26454
Opened 2023-08-18 05:08 UTC by weiliu1031

Signed-off-by: Wei Liu <wei.liu@zilliz.com>
issue: #26451

2023-08-18 07:20 UTC, yah01 requested changes

2023-08-18 07:20 UTC, yah01 commented on internal/querynodev2/services.go
> +	if node.unsubscribingChannels.Contain(channel.GetChannelName()) {
how does this work if the unsubscribing is coming but has not modified the `unsubscribingChannels`?

2023-08-18 07:20 UTC, yah01 commented on internal/querynodev2/services.go
>  	delegator, ok := node.delegators.GetAndRemove(req.GetChannelName())
Use `defer` to make it always work even new `return` inserted

2023-08-18 08:57 UTC, weiliu1031 commented
/run-cpu-e2e

2023-08-22 14:18 UTC, xiaofan-luan commented
/lgtm
/approve

2023-08-23 02:06 UTC, congqixia approved these changes
/lgtm

2023-08-23 02:10 UTC, merged