ADD query operate to find if pk exist when upsert
milvus-io/milvus pull request #26551
Opened 2023-08-22 11:41 UTC by smellthemoon

/kind improvement
#25633

2023-08-29 13:57 UTC, smellthemoon commented
rerun ut

2023-08-29 14:11 UTC, smellthemoon commented
rerun ut

2023-08-30 03:26 UTC, smellthemoon commented on internal/proxy/task_upsert.go
> +		ConsistencyLevel:   commonpb.ConsistencyLevel_Strong,
it's ok to not use strong here, use strong here to try to make query more accurate, than can delete less.

2023-08-30 03:52 UTC, yah01 requested changes

2023-08-30 03:52 UTC, yah01 commented on internal/proxy/task_upsert.go
> +	needDeletePrimaryKey *schemapb.IDs
rename to `deletePrimaryKeys`

2023-08-30 03:52 UTC, yah01 commented on internal/proxy/impl.go
> +		req.CollectionID, err = globalMetaCache.GetCollectionID(ctx, req.GetDbName(), req.GetCollectionName())
move these into another PRs

2023-08-30 03:52 UTC, yah01 commented on internal/proxy/task_upsert.go
> +			strings.Contains(err.Error(), merr.ErrPartitionNotFullyLoaded.Error()) {
use `errors.Is(err, merr.ErrXxx)` to assert errors, don't use string containing

2023-08-30 03:52 UTC, yah01 commented on internal/proxy/task_upsert.go
> +	err = merr.Error(queryResult.GetStatus())
all logic from here to end of this method, should be moved out to line 356

2023-08-30 03:52 UTC, yah01 commented on internal/proxy/task_upsert.go
> +			log.Info("DeleteCnt are more than InsertCnt when upsert",
use warning level log as it not normal

2023-08-30 03:52 UTC, yah01 commented on internal/proxy/task_upsert.go
> +			return merr.WrapErrParameterInvalid("DeleteCnt less than or equal to InsertCnt when upsert", "not")
use `WrapErrParameterInvalidRange`

2023-08-30 07:06 UTC, yah01 commented on internal/proxy/task_upsert.go
> +			errors.Is(err, merr.ErrCollectionNotFullyLoaded) || errors.Is(err, merr.ErrPartitionNotFullyLoaded) {
-> `errors.IsAny(err, merr.ErrXxx, merr.ErrYyy)`

2023-08-31 02:28 UTC, yah01 commented on internal/proxy/task_upsert.go
> +			zap.Error(err), zap.Any("reason", queryResult.GetStatus().Reason))
the err that converted from status by merr contains the reason, the two log fields would produce dup messages, remove the `reason` field

2023-08-31 02:28 UTC, yah01 commented on internal/proxy/task_upsert.go
> +			return err
the logic is correct, but the org is not clear. try to reorg it like:
```
if errors.Is(err, Xxx, Yyy) {
    //...
} else if err != nil {
    //...
} else {
    //...
}

2023-09-01 02:25 UTC, smellthemoon commented
rerun ut

2023-09-01 10:10 UTC, smellthemoon commented
rerun ut

2023-09-02 12:56 UTC, xiaofan-luan commented on internal/proxy/impl.go
> +	upsertReceiveSize := insertReceiveSize + it.queryReceiveSize
what is queryReceiveSize mean?
When we rate limit upsert I think we should evaluate more on delete and insert?

2023-09-02 13:03 UTC, xiaofan-luan commented on internal/proxy/task_upsert.go
> +		stats, ts, err := ticker.getMinTsStatistics()
what does ticker.getMinTsStatistics mean?

I think the query should use the upsert ts?

2023-09-02 13:05 UTC, xiaofan-luan commented on internal/proxy/task_upsert.go
> +	queryResult, err := it.queryPK()
the queryPK has to be configurable.
This might affect the upsert performance because it has to be strong consistency

2023-09-02 13:08 UTC, xiaofan-luan commented on internal/proxy/task_upsert.go
> +		ConsistencyLevel:   commonpb.ConsistencyLevel_Strong,
> 

If not use strong consistency, then you may miss delete of the old data right?

2023-09-02 13:08 UTC, xiaofan-luan commented on internal/proxy/task_upsert.go
> +		ConsistencyLevel:   commonpb.ConsistencyLevel_Strong,
Also I don't think this has to strong
 You actaully need to specify timestamp to the same of upsert to the query

2023-09-08 07:27 UTC, smellthemoon commented
Close temporarily until lognode completes.

2023-09-08 07:27 UTC, closed without merging