fix false load failure for long unserviable period(#26813)
milvus-io/milvus pull request #26818
Opened 2023-09-04 02:47 UTC by MrPresent-Han

related: #26813

2023-09-04 11:27 UTC, MrPresent-Han commented
rerun ut

2023-09-06 02:27 UTC, congqixia commented
/milestone 2.3.1

2023-09-06 02:30 UTC, yah01 approved these changes
/lgtm

2023-09-06 02:31 UTC, yah01 commented
/cc @congqixia

2023-09-06 02:50 UTC, congqixia requested changes

2023-09-06 02:50 UTC, congqixia commented on internal/querynodev2/delegator/delegator_data.go
> +	sd.distribution.AddDistributions(entries...)
altering distribution shall be protected by delete lock otherwise some delete entry might be missed

2023-09-06 03:30 UTC, MrPresent-Han commented
/run-cpu-e2e

2023-09-06 04:11 UTC, congqixia approved these changes
/lgtm

2023-09-06 04:57 UTC, merged