Refactor flush, flush by flush channels
milvus-io/milvus pull request #26859
Opened 2023-09-05 13:02 UTC by bigsheeper

issue: https://github.com/milvus-io/milvus/issues/26820

/kind bug

2023-09-07 08:22 UTC, bigsheeper commented
/run-cpu-e2e

2023-09-07 14:54 UTC, bigsheeper commented
/run-cpu-e2e

2023-09-07 14:55 UTC, bigsheeper commented
rerun ut

2023-09-08 03:59 UTC, bigsheeper commented
/run-cpu-e2e

2023-09-08 06:33 UTC, xiaofan-luan commented
please fix the flush message

2023-09-08 06:34 UTC, XuanYang-cn commented on internal/types/types.go
>  	// GetFlushState gets the flush state of multiple segments
need to update this comment

2023-09-08 06:37 UTC, XuanYang-cn commented on internal/datacoord/services.go
> +		zap.Uint64("flushTs", ts))
perhaps transfer ts into human readable time.Time for readability

2023-09-08 06:44 UTC, XuanYang-cn commented on internal/datanode/channel_meta.go
> +		flushTs:      atomic.NewUint64(math.MaxUint64),
why new segments have the maxUint64 as flushTs, why not 0

2023-09-08 07:02 UTC, XuanYang-cn commented on internal/datanode/channel_meta.go
> +	flushTs *atomic.Uint64
So its a minTs for channel to flush all streaming data <= flushTs into S3, which means to trigger a sync when bufferred segments ts >= flushTs, and update cp if buffered channelCP.ts reaches flustTs, took me a while to understands the meaning of the param.

Perhaps rename it with syncThreshold, means any segments whose buffer exceeds the thresholds with be synced

and set a const NoThreshold = math.MaxInt64, cuz math.MaxInt64 do make people wonder why when reading codes

2023-09-08 07:05 UTC, XuanYang-cn commented on internal/datanode/channel_meta.go
> +	flushTs *atomic.Uint64
setSyncThreshold(ts)

cleanSyncThreahold/resetSyncThreshold or ....

would be betther to replace setFlushts

2023-09-08 07:08 UTC, XuanYang-cn requested changes
Over all LGTM, just mentioned some readbility suggestions

2023-09-11 11:54 UTC, xiaofan-luan commented on internal/datacoord/services.go
> +		resp.Status = merr.Status(err)
log the error?

2023-09-11 12:12 UTC, xiaofan-luan reviewed
/approve

2023-09-12 01:52 UTC, bigsheeper commented
rerun ut

2023-09-12 13:06 UTC, xiaofan-luan commented
/lgtm

2023-09-12 13:07 UTC, merged