fix false handle for describe index response(#25363)
milvus-io/milvus pull request #27247
Opened 2023-09-20 02:09 UTC by MrPresent-Han

related: #25363

2023-09-21 07:51 UTC, MrPresent-Han commented
rerun ut

2023-09-21 10:22 UTC, MrPresent-Han commented
rerun ut

2023-09-21 11:50 UTC, MrPresent-Han commented
rerun ut

2023-09-27 01:56 UTC, MrPresent-Han commented
rerun ut

2023-09-27 05:35 UTC, MrPresent-Han commented
rerun ut

2023-09-27 11:25 UTC, congqixia requested changes

2023-09-27 11:25 UTC, congqixia commented on internal/querycoordv2/meta/coordinator_broker.go
> +	resp, _ := broker.dataCoord.DescribeIndex(ctx, &indexpb.DescribeIndexRequest{
We could not ignore grpc error here

2023-09-27 11:25 UTC, congqixia commented on internal/querycoordv2/job/utils.go
> -	}
we could not simply remove describe index here
index shall exist before loading
any suggestion here @yah01 @weiliu1031

2023-10-09 02:03 UTC, closed without merging