Add some log for delete task when it need query
milvus-io/milvus pull request #27317
Opened 2023-09-22 07:54 UTC by aoiasd

/related https://github.com/milvus-io/milvus/issues/25751

2023-09-25 02:33 UTC, aoiasd commented
/run-cpu-e2e

2023-10-07 08:30 UTC, aoiasd commented
/run-cpu-e2e

2023-10-20 06:11 UTC, aoiasd commented
/run-cpu-e2e

2023-10-23 06:45 UTC, yah01 requested changes

2023-10-23 06:45 UTC, yah01 commented on internal/proxy/task_delete.go
> +					log.Info("query stream for delete finished", zap.Int64("msgID", dt.msgID), zap.Duration("duration", rc.ElapseSpan()))
Change it to debug level or maybe produce many logs

2023-10-23 06:45 UTC, yah01 commented on internal/proxy/task_delete.go
> +		log.Debug("start query for delete",
use
```golang
log := log.Ctx(ctx).With(
    zap.Int64("collectionID", dt.collectionID),
    ...
)
```
and remove these fields from line 360

2023-10-24 06:52 UTC, congqixia approved these changes
/lgtm

2023-10-24 06:54 UTC, merged