Reduce goroutine resulting from GetIndexInfos
milvus-io/milvus pull request #27547
Opened 2023-10-09 03:50 UTC by bigsheeper

issue: https://github.com/milvus-io/milvus/issues/27545

/kind enhancement

No need to pick to master, because indexCoord has been merged to dataCoord.

2023-10-09 03:56 UTC, yah01 approved these changes
/lgtm

2023-10-09 13:35 UTC, xiaofan-luan commented
when did we call GetIndexinfos?

2023-10-10 02:02 UTC, bigsheeper commented
> when did we call GetIndexinfos?

To verify whether a segment has been indexed, for example during compaction or GetRecoveryInfo.

2023-10-10 10:13 UTC, yah01 requested changes

2023-10-10 10:13 UTC, yah01 commented on internal/datacoord/util.go
> +	if resp.GetStatus().GetErrorCode() != commonpb.ErrorCode_Success {
use the new error handling way:
```
err := merr.CheckRPCCall(resp, err)
if err != nil {
// ...
}
```

2023-10-10 12:15 UTC, bigsheeper commented on internal/datacoord/util.go
> +	if resp.GetStatus().GetErrorCode() != commonpb.ErrorCode_Success {
this is 2.2.x branch, so no merr

2023-10-10 15:52 UTC, yah01 reviewed
/lgtm

2023-10-11 07:27 UTC, czs007 commented on internal/datacoord/util.go
> +		log.Warn("failed to get index of collection",
better to use log.Info

2023-10-11 07:28 UTC, czs007 commented on internal/datacoord/util.go
> +		log.Warn("indexcoord return error when get index",
better to use Info level

2023-10-11 07:40 UTC, czs007 commented
/approve

2023-10-11 07:43 UTC, merged