Schedule loading L0 segments first
milvus-io/milvus pull request #27593
Opened 2023-10-10 07:20 UTC by yah01

/kind feature
related #27349

2023-10-17 08:23 UTC, yah01 commented
/run-cpu-e2e

2023-10-17 08:52 UTC, yah01 commented
/run-cpu-e2e

2023-10-17 10:10 UTC, yah01 commented
/run-cpu-e2e

2023-10-17 10:19 UTC, yah01 commented
/run-cpu-e2e

2023-10-18 07:24 UTC, congqixia requested changes

2023-10-18 07:24 UTC, congqixia commented on internal/querycoordv2/checkers/segment_checker.go
> +	distMap := typeutil.NewConcurrentMap[int64, int64]()
why use concurrent map here? this map is used only in this method

2023-10-18 07:24 UTC, congqixia commented on internal/querycoordv2/checkers/segment_checker.go
> +		leader := c.dist.LeaderViewManager.GetLatestLeadersByShard(segment.GetInsertChannel())
this leader could be a leader from other replica

2023-10-18 10:38 UTC, yah01 commented
rerun ut

2023-10-19 03:12 UTC, congqixia approved these changes
/lgtm

2023-10-19 03:13 UTC, congqixia approved these changes
/lgtm

2023-10-19 03:14 UTC, merged