refine stop order
milvus-io/milvus pull request #27897
Opened 2023-10-24 13:37 UTC by weiliu1031

issue: #27896

2023-10-24 13:44 UTC, congqixia requested changes
coordinators shall stop in parallel

2023-10-25 02:00 UTC, weiliu1031 commented
/hold

2023-10-25 02:17 UTC, jaime0815 commented
stop order should be proxy -> node -> coord,  the client request will not execute successfully if stop coord component firstly.

2023-10-30 05:53 UTC, weiliu1031 commented
rerun ut

2023-10-30 08:11 UTC, closed without merging