fix: update binlog index memory uasge before loading segments
milvus-io/milvus pull request #28528
Opened 2023-11-17 06:04 UTC by cqy123456

issue: #27678 
when interimIndex = true, memory predict should be update with the memory usage of binlog index build process.

2023-11-17 06:38 UTC, cqy123456 commented
/run-cpu-e2e

2023-11-20 06:45 UTC, cqy123456 commented
/run-cpu-e2e

2023-11-20 07:40 UTC, cqy123456 commented
/run-cpu-e2e

2023-11-27 10:51 UTC, cqy123456 commented
rerun ut

2023-11-28 02:21 UTC, yah01 commented
/lgtm

2023-11-28 02:26 UTC, congqixia requested changes

2023-11-28 02:26 UTC, congqixia commented on internal/querynodev2/segments/segment_loader.go
>  )
please add these magic number into paramtable instead of using const here

2023-11-28 02:40 UTC, bigsheeper commented
/lgtm

2023-11-28 13:32 UTC, cqy123456 commented
/run-cpu-e2e

2023-11-28 14:46 UTC, cqy123456 commented
/run-cpu-e2e

2023-11-28 15:05 UTC, cqy123456 commented
/run-cpu-e2e

2023-11-29 02:06 UTC, yah01 commented
/run-cpu-e2e

2023-11-29 06:21 UTC, cqy123456 commented
/run-cpu-e2e

2023-11-29 07:16 UTC, yah01 commented
/run-cpu-e2e

2023-11-29 08:40 UTC, congqixia approved these changes
/lgtm

2023-11-29 08:42 UTC, merged