Fix: frequent flush cause minio rate limit
milvus-io/milvus pull request #28625
Opened 2023-11-21 14:12 UTC by xiaofan-luan

related to #28549

1. avoid duplicated sync segments under syncing states
2. add jitter to avoid sync segments at the same time

2023-11-21 14:37 UTC, xiaofan-luan commented
/run-cpu-e2e

2023-11-22 02:21 UTC, bigsheeper commented
Actually, there is a logic to avoid duplicated sync segments:
https://github.com/milvus-io/milvus/blob/0fbd610e89d0e00eaaa93973f122fb9962710294/internal/datanode/flow_graph_insert_buffer_node.go#L468

2023-11-22 03:09 UTC, XuanYang-cn commented
> Actually, there is a logic to avoid duplicated sync segments:
> 
> https://github.com/milvus-io/milvus/blob/0fbd610e89d0e00eaaa93973f122fb9962710294/internal/datanode/flow_graph_insert_buffer_node.go#L468

@bigsheeper  This checks when executing tasks, which is too late. we're generating way too many sync tasks,  logging them and merging them, but not executing them, which's very confusing. It's betther we ignore the syncing segment while generating sync task, more efficient.

2023-11-22 03:11 UTC, XuanYang-cn requested changes

2023-11-22 03:11 UTC, XuanYang-cn commented on internal/datanode/flush_manager.go
> +			log.Warn("failed to flush insert data", zap.Error(err))
I don't think this is the right place to log failed to flush, its `err==nil` above

2023-11-22 03:11 UTC, XuanYang-cn commented on internal/datanode/flush_manager.go
> +				log.Warn("failed to flush delete data", zap.Error(err))
ditto

2023-12-10 13:27 UTC, xiaofan-luan commented
/run-cpu-e2e

2023-12-10 14:43 UTC, xiaofan-luan commented
/run-cpu-e2e

2023-12-10 14:47 UTC, xiaofan-luan commented
/run-cpu-e2e

2023-12-10 14:52 UTC, xiaofan-luan commented
/run-cpu-e2e

2023-12-11 09:59 UTC, xiaofan-luan commented
/run-cpu-e2e

2023-12-13 08:03 UTC, xiaofan-luan commented
/run-cpu-e2e

2023-12-13 08:35 UTC, xiaofan-luan commented
/run-cpu-e2e

2023-12-13 10:13 UTC, xiaofan-luan commented
/run-cpu-e2e

2023-12-13 13:53 UTC, xiaofan-luan commented
/run-cpu-e2e

2023-12-14 04:01 UTC, xiaofan-luan commented
/run-cpu-e2e

2023-12-14 08:13 UTC, xiaofan-luan commented
/run-cpu-e2e

2023-12-14 08:43 UTC, xiaofan-luan commented
/run-cpu-e2e

2023-12-14 13:44 UTC, xiaofan-luan commented
/run-cpu-e2e

2023-12-15 01:29 UTC, xiaofan-luan commented
/run-cpu-e2e

2023-12-17 14:52 UTC, xiaofan-luan commented
/run-cpu-e2e

2023-12-17 15:14 UTC, xiaofan-luan commented
/run-cpu-e2e

2023-12-17 15:22 UTC, xiaofan-luan commented
/run-cpu-e2e

2023-12-19 06:04 UTC, xiaofan-luan commented
/run-cpu-e2e

2023-12-19 06:11 UTC, xiaofan-luan commented
/run-cpu-e2e

2023-12-20 07:02 UTC, merged