Fix: balance channel may cause channel not availble error
milvus-io/milvus pull request #28829
Opened 2023-11-29 09:24 UTC by weiliu1031

release old delegator before new delegator update it's distribution may cause `channel not availble` error

This PR will block release old delgator before new delegator finish `syncDistribution`

2023-11-29 10:39 UTC, yah01 requested changes

2023-11-29 10:39 UTC, yah01 commented on internal/querycoordv2/task/scheduler.go
> +		segmentsInTarget := scheduler.targetMgr.GetSealedSegmentsByChannel(collectionID, channel, meta.CurrentTarget)
Move these into the channel task's `IsSucceeded` method

2023-11-29 10:45 UTC, yah01 approved these changes
/lgtm

2023-11-30 08:14 UTC, weiliu1031 commented
/run-cpu-e2e

2023-12-01 02:02 UTC, yah01 reviewed
/lgtm

2023-12-01 02:07 UTC, congqixia approved these changes
/approve

2023-12-01 02:08 UTC, merged