Add new gpu index:GPU_BRUTE_FORCE
milvus-io/milvus pull request #29590
Opened 2023-12-29 05:22 UTC by cqy123456

2023-12-29 11:40 UTC, czs007 commented
rerun ut

2023-12-31 09:37 UTC, czs007 commented
@cqy123456  please run clang-format to fix the code check  issue

2024-01-02 11:44 UTC, cqy123456 commented
rerun ut

2024-01-03 06:11 UTC, cqy123456 commented
rerun ut

2024-01-03 11:09 UTC, cqy123456 commented
rerun ut

2024-01-03 12:09 UTC, cqy123456 commented
rerun ut

2024-01-04 06:06 UTC, cqy123456 commented
rerun ut

2024-01-04 07:01 UTC, cqy123456 commented
/run-cpu-e2e

2024-01-04 09:52 UTC, yah01 requested changes

2024-01-04 09:52 UTC, yah01 commented on internal/core/src/config/ConfigKnowhere.cpp
> +        PanicInfo(ConfigInvalid,
try this:
```
PanicInfo(ConfigInvalid,
                  "Error Gpu memory pool params: init_size {} can't not large "
                  "than max_size {}.", init_size, max_size);
```

2024-01-04 09:52 UTC, yah01 commented on pkg/util/indexparamcheck/raft_ivf_pq_checker.go
> +		return fmt.Errorf("metric type not found or not supported, supported: %v", RaftMetrics)
->
```
return merr.WrapErrMetricNotFound(RaftMetrics)
```

2024-01-04 11:00 UTC, czs007 commented on pkg/util/indexparamcheck/raft_ivf_pq_checker_test.go
> +		{p3, false},
why?

2024-01-04 11:12 UTC, cqy123456 commented on pkg/util/indexparamcheck/raft_ivf_pq_checker.go
> +		return fmt.Errorf("metric type not found or not supported, supported: %v", RaftMetrics)
import cycle

2024-01-04 11:12 UTC, cqy123456 commented on internal/core/src/config/ConfigKnowhere.cpp
> +        PanicInfo(ConfigInvalid,
updated

2024-01-04 11:14 UTC, czs007 commented
/approve

2024-01-04 11:21 UTC, cqy123456 commented on pkg/util/indexparamcheck/raft_ivf_pq_checker_test.go
> +		{p3, false},
GPU index not support cosine metric now

2024-01-05 02:11 UTC, cqy123456 commented
/run-cpu-e2e

2024-01-05 02:12 UTC, cqy123456 commented
rerun ut

2024-01-05 02:29 UTC, cqy123456 commented
/run-cpu-e2e

2024-01-05 04:48 UTC, samhuang-z commented
rerun ut

2024-01-05 07:22 UTC, yah01 commented
/lgtm

2024-01-05 07:24 UTC, merged