feat: Implement DescribeAlias and ListAliases interfaces
milvus-io/milvus pull request #29641
Opened 2024-01-03 09:17 UTC by wayblink

#22882
/kind feature

2024-01-04 08:39 UTC, wayblink commented
rerun ut

2024-01-05 04:48 UTC, samhuang-z commented
rerun ut

2024-01-07 02:58 UTC, wayblink commented
rerun ut

2024-01-08 10:39 UTC, wayblink commented
rerun ut

2024-01-08 11:31 UTC, czs007 commented
/approve
/lgtm

2024-01-08 11:32 UTC, czs007 commented
please pick to 2.3 after merged

2024-01-08 12:15 UTC, longjiquan requested changes

2024-01-08 12:15 UTC, longjiquan commented on internal/rootcoord/root_coord.go
> +	log.Info("done to list aliases",
Ditto.

2024-01-09 02:13 UTC, czs007 commented
/lgtm

2024-01-09 06:15 UTC, wayblink commented
rerun ut

2024-01-09 12:03 UTC, wayblink commented
rerun ut

2024-01-11 11:11 UTC, czs007 commented
/lgtm

2024-01-11 11:12 UTC, merged