enhance: skip loading duplicated index
milvus-io/milvus pull request #29715
Opened 2024-01-05 06:46 UTC by yah01

this protect the loading index from failure, and speed up the loading progress

2024-01-05 06:54 UTC, yah01 commented
/run-cpu-e2e

2024-01-05 07:03 UTC, yah01 commented
/run-cpu-e2e

2024-01-07 15:47 UTC, yah01 commented
rerun ut

2024-01-08 09:18 UTC, yah01 commented
rerun ut

2024-01-09 02:42 UTC, samhuang-z commented
rerun ut

2024-01-10 08:20 UTC, congqixia requested changes

2024-01-10 08:20 UTC, congqixia commented on internal/querynodev2/segments/segment.go
> +	}
```suggestion
	loadIndexInfo, err := newLoadIndexInfo(ctx)
	if err != nil {
		return err
	}
	defer deleteLoadIndexInfo(loadIndexInfo)
```

2024-01-10 09:26 UTC, yah01 commented
/run-cpu-e2e

2024-01-11 03:50 UTC, congqixia approved these changes
/lgtm

2024-01-11 03:52 UTC, merged