support groupby based on scalar-index(#29965)
milvus-io/milvus pull request #30091
Opened 2024-01-18 06:19 UTC by MrPresent-Han

related: #29965

2024-01-19 02:55 UTC, yah01 requested changes

2024-01-19 02:55 UTC, yah01 commented on internal/core/src/segcore/Reduce.cpp
>                      *(field_data->mutable_data()->Add()) = val;
Move to avoid copying

2024-01-19 02:55 UTC, yah01 commented on internal/core/unittest/test_group_by.cpp
>                  strs_set.insert(g_val);
Move to avoid copying

2024-01-19 07:40 UTC, MrPresent-Han commented on internal/core/src/segcore/Reduce.cpp
>                      *(field_data->mutable_data()->Add()) = val;
changed

2024-01-19 07:40 UTC, MrPresent-Han commented on internal/core/unittest/test_group_by.cpp
>                  strs_set.insert(g_val);
changed

2024-01-19 07:45 UTC, yah01 reviewed
/lgtm

2024-01-22 02:49 UTC, congqixia commented
/approve

2024-01-22 02:50 UTC, merged