enhance: add addition index params for raft index
milvus-io/milvus pull request #30179
Opened 2024-01-22 06:39 UTC by cqy123456

2024-01-23 06:55 UTC, cqy123456 commented
/run-cpu-e2e

2024-01-23 07:10 UTC, cqy123456 commented
/run-cpu-e2e

2024-01-26 09:51 UTC, cqy123456 commented
/run-cpu-e2e

2024-01-28 13:33 UTC, cqy123456 commented
/run-cpu-e2e

2024-01-28 13:33 UTC, cqy123456 commented
rerun ut

2024-01-28 15:35 UTC, cqy123456 commented
/run-cpu-e2e

2024-01-29 07:43 UTC, yah01 approved these changes
/lgtm

2024-01-29 07:51 UTC, cqy123456 commented
/run-cpu-e2e

2024-02-22 03:32 UTC, cqy123456 commented
/run-cpu-e2e

2024-02-22 10:02 UTC, cqy123456 commented
rerun ut

2024-02-23 06:32 UTC, longjiquan requested changes

2024-02-23 06:32 UTC, longjiquan commented on pkg/util/indexparamcheck/constraints.go
> +	CagraBuildAlgoType        = []string{CargaBuildAlgoIVFPQ, CargaBuildAlgoNNDESCENT}
Maybe `CagraBuildAlgoTypes` is better.

2024-02-23 06:32 UTC, longjiquan commented on pkg/util/indexparamcheck/raft_ivf_pq_checker.go
> +		return fmt.Errorf("raft index cache_dataset_on_device param only support true false")
Add ut for this case.

2024-02-26 06:25 UTC, longjiquan reviewed
/lgtm

2024-02-26 06:50 UTC, czs007 commented
/approve

2024-02-26 06:50 UTC, merged