modfied IndexIDMAP.cpp && SearchTask.cpp
milvus-io/milvus pull request #3211
Opened 2020-08-10 20:31 UTC by MXDA

Signed-off-by: Zhengda Wu <wuzhengda55@gmail.com>

**What type of PR is this?**
- [ ] Feature

**Which branch you want to cherry-pick to?**
0.10.2

**Which issue(s) this PR fixes:**
Fixes #

**What this PR does / why we need it:**
Specifying distance type at runtime for Flat index

**Special notes for your reviewer:**
Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available
Fixes #
Fixes #

2020-08-12 06:43 UTC, shengjun1985 approved these changes

2020-08-13 02:44 UTC, wxyucs approved these changes

2020-08-13 13:17 UTC, shengjun1985 requested changes
You miss MappingMetricType in ExecutionEngineImpl.cpp

2020-08-13 13:17 UTC, shengjun1985 commented on core/src/scheduler/task/SearchTask.cpp
>          }
Please use knowhere::Metric::TYPE instead of "metric_type".

2020-08-14 06:29 UTC, shengjun1985 approved these changes

2020-08-15 08:29 UTC, shengjun1985 commented
@MXDA
You have done a good job. But v0.10.2 is released today.
Would you like to create a new PR to 0.10.3?

Furthermore, it would be greater if you continue to complete the following two tasks:
(1) modify "IndexGPUIDMAP.cpp" as "IndexIDMAP.cpp" to support GPU version
(2) introduce your new feature in "CHANGELOG.md"

Thank you very much.

2020-08-15 08:29 UTC, closed without merging