enhance: Query slot for compaction task
milvus-io/milvus pull request #32881
Opened 2024-05-09 02:55 UTC by bigsheeper

Query slot of compaction in datanode, and transfer the control logic for limiting compaction tasks from datacoord to the datanode.

issue: https://github.com/milvus-io/milvus/issues/32809

2024-05-11 02:07 UTC, bigsheeper commented
/run-cpu-e2e

2024-05-13 08:11 UTC, XuanYang-cn requested changes

2024-05-14 07:28 UTC, bigsheeper commented on internal/datacoord/compaction_scheduler.go
> +}
done

2024-05-15 10:06 UTC, XuanYang-cn commented
/lgtm

2024-05-17 03:00 UTC, bigsheeper commented
rerun ut

2024-05-17 10:07 UTC, czs007 commented on internal/datacoord/compaction_scheduler.go
>  	s.taskGuard.Lock()
Rlock

2024-05-17 10:13 UTC, czs007 commented on internal/proto/data_coord.proto
> +  int64 num_slots = 2;
add nodeID

2024-05-17 10:17 UTC, czs007 commented
/approve
/lgtm

2024-05-17 10:19 UTC, merged