enhance: load deltalogs on demand when doing compactions
milvus-io/milvus pull request #37310
Opened 2024-10-30 11:18 UTC by tedxu

See #37234

2024-10-31 02:02 UTC, tedxu commented
/run-cpu-e2e

2024-10-31 07:07 UTC, XuanYang-cn requested changes

2024-10-31 07:07 UTC, XuanYang-cn commented on internal/datanode/compaction/merge_sort.go
> +		}
Please record `deletedRowCount` here

2024-10-31 09:26 UTC, tedxu commented
/run-cpu-e2e

2024-11-01 06:42 UTC, XuanYang-cn approved these changes
/lgtm

2024-11-01 08:39 UTC, congqixia approved these changes
/approve

2024-11-01 08:40 UTC, merged