enhance: unmashall ts msg in dispatcher instead in msgstream
milvus-io/milvus pull request #38656
Opened 2024-12-23 06:32 UTC by aoiasd

relate: https://github.com/milvus-io/milvus/issues/38655

2025-01-16 07:08 UTC, aoiasd commented
rerun cpp-unit-test

2025-01-16 07:08 UTC, aoiasd commented
/run-cpu-e2e

2025-01-16 07:08 UTC, aoiasd commented
rerun go-sdk

2025-02-11 03:49 UTC, XuanYang-cn requested changes

2025-02-11 03:49 UTC, XuanYang-cn commented on pkg/mq/msgstream/msgstream.go
> +type PackMsg interface {
Maybe rename to ConsumedMsg, ConsumedMsgPack.

PackMsg is too confused with MsgPack.

2025-02-11 03:49 UTC, XuanYang-cn commented on pkg/mq/msgstream/msgstream.go
> +type PackMsg interface {
Please check UnmarshalledMsg and MarshelledMsg is ConsumedMsg interface

2025-02-13 02:20 UTC, aoiasd commented
rerun go-sdk

2025-02-14 03:42 UTC, XuanYang-cn approved these changes
/lgtm

2025-02-14 04:02 UTC, congqixia commented
/approve

2025-02-14 04:04 UTC, merged