ResfulApi Search return null
milvus-io/milvus pull request #4117
Opened 2020-10-28 07:23 UTC by fishpenguin

Signed-off-by: fishpenguin <kun.yu@zilliz.com>

**What type of PR is this?**

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

Fixes #4116 

**What this PR does / why we need it:**

Not Available

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

2020-10-28 08:37 UTC, BossZou submitted a review, later dismissed

2020-10-28 14:23 UTC, scsven requested changes

2020-10-28 14:23 UTC, scsven commented on core/src/server/web_impl/handler/WebRequestHandler.cpp
> +            nlohmann::json data_json;
Use milvus::json instead.

2020-11-02 02:52 UTC, scsven approved these changes, later dismissed

2020-11-09 14:02 UTC, scsven approved these changes

2020-11-09 14:03 UTC, merged