The scalar field information of search result is wrong after some ent…
milvus-io/milvus pull request #4209
Opened 2020-11-10 08:52 UTC by BossZou

…ities deleted

Signed-off-by: Yhz <yinghao.zou@zilliz.com>

**What type of PR is this?**

- [ ] API-change
- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

Fixes #4200

**What this PR does / why we need it:**

Fix bug.

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

2020-11-11 02:03 UTC, scsven requested changes

2020-11-11 02:03 UTC, scsven commented on core/src/server/delivery/request/SearchReq.cpp
> +                bool is_binary = !(field->GetFtype() == engine::DataType::VECTOR_FLOAT);
Simplified to `!=`

2020-11-11 07:14 UTC, BossZou commented on core/src/server/delivery/request/SearchReq.cpp
> +                bool is_binary = !(field->GetFtype() == engine::DataType::VECTOR_FLOAT);
Fixed.

2020-11-11 09:42 UTC, scsven approved these changes, later dismissed

2020-11-11 10:44 UTC, yhmo approved these changes

2020-11-11 10:44 UTC, yhmo commented on core/src/server/delivery/request/SearchReq.cpp
> +                bool is_binary = field->GetFtype() != engine::DataType::VECTOR_FLOAT;
bool is_binary = (field->GetFtype() != engine::DataType::VECTOR_FLOAT);

2020-11-11 11:19 UTC, BossZou commented on core/src/server/delivery/request/SearchReq.cpp
> +                bool is_binary = field->GetFtype() != engine::DataType::VECTOR_FLOAT;
Changed.

2020-11-12 09:54 UTC, cydrain approved these changes

2020-11-14 02:42 UTC, scsven approved these changes

2020-11-14 02:42 UTC, merged