Add an optional parameter naming 'client_tag'  on client constructor in c++ sdk
milvus-io/milvus pull request #4377
Opened 2020-12-04 11:57 UTC by fishpenguin

Signed-off-by: fishpenguin <kun.yu@zilliz.com>

**What type of PR is this?**

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

Fixes #4376 

**What this PR does / why we need it:**

Not Available

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

2020-12-07 02:53 UTC, scsven requested changes

2020-12-07 02:53 UTC, scsven commented on sdk/grpc/ClientProxy.h
> + class ClientProxy : public Connection , public GrpcInterceptorHookHandler {
Wrong indent

2020-12-07 03:10 UTC, fishpenguin commented on sdk/grpc/ClientProxy.h
> + class ClientProxy : public Connection , public GrpcInterceptorHookHandler {
Fixed

2020-12-08 10:30 UTC, scsven approved these changes

2020-12-09 02:36 UTC, merged