[skip ci] Update links and fix dead links.
milvus-io/milvus pull request #4496
Opened 2020-12-22 11:19 UTC by ireneontheway5

Signed-off-by: ireneontheway5 <qingying.hu@zilliz.com>

**What type of PR is this?**

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [x] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

Fixes #

**What this PR does / why we need it:**

Not Available

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

2020-12-23 02:46 UTC, JinHai-CN submitted a review, later dismissed

2020-12-24 03:49 UTC, ireneontheway5 commented on SUPPORT.md
>  -   [FAQ](https://www.milvus.io/docs/v0.6.0/faq/operational_faq.md)
```suggestion
-   [FAQ](https://www.milvus.io/docs/operational_faq.md)
```

2020-12-24 03:54 UTC, ireneontheway5 commented on docs/test_report/milvus_ivfsq8h_test_report_detailed_version_cn.md
> +Milvus设置的详细定义可以参考 https://milvus.io/docs/milvus_config.md 。
```suggestion
Milvus设置的详细定义可以参考 https://milvus.io/cn/docs/milvus_config.md 。
```

2020-12-25 06:51 UTC, PahudPlus requested changes

2020-12-25 06:51 UTC, PahudPlus commented on docs/test_report/ivfflat_test_report_cn.md
> +Milvus设置的详细定义可以参考 https://milvus.io/cn/docs/milvus_config.md 。
Remove additional space between md and the full stop.

2020-12-25 09:50 UTC, scsven approved these changes

2020-12-25 09:54 UTC, JinHai-CN commented
LGTM!

2020-12-25 09:54 UTC, JinHai-CN approved these changes

2020-12-25 09:58 UTC, XuPeng-SH approved these changes

2020-12-25 11:55 UTC, yhmo approved these changes

2020-12-25 11:55 UTC, merged