[skip ci] Update README.md.
milvus-io/milvus pull request #4589
Opened 2021-01-08 07:32 UTC by ireneontheway5

Signed-off-by: ireneontheway5 <qingying.hu@zilliz.com>

**What type of PR is this?**

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [x] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

Fixes #

**What this PR does / why we need it:**

Not Available

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

2021-01-09 04:06 UTC, PahudPlus requested changes

2021-01-11 06:36 UTC, PahudPlus requested changes

2021-01-11 06:36 UTC, PahudPlus commented on README.md
> +Milvus is a vector similarity search engine that is highly flexible, reliable, and blazing fast. It supports adding, deleting, updating, and near-real-time search of embeddings on a scale of trillion
embedding vectors

2021-01-11 06:42 UTC, PahudPlus approved these changes

2021-01-12 02:58 UTC, JinHai-CN approved these changes

2021-01-12 02:59 UTC, merged