[skip ci] contributing&readme_proofread
milvus-io/milvus pull request #4919
Opened 2021-04-12 08:25 UTC by LocoRichard

Signed-off-by: LocoRichard <lichen.wang@zilliz.com>

**What type of PR is this?**

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

Fixes #

**What this PR does / why we need it:**

Not Available

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

2021-04-12 09:38 UTC, YiyunNi commented on CONTRIBUTING.md
> +The following are a set of guidelines for contributing to Milvus. Following these guidelines makes contributing to this project easy and transparent. These are mostly guideline, not rules. Use your b
guidelines

2021-04-12 09:38 UTC, YiyunNi commented on CONTRIBUTING.md
> +The following are a set of guidelines for contributing to Milvus. Following these guidelines makes contributing to this project easy and transparent. These are mostly guideline, not rules. Use your b
These are mostly guideline**s**, not rules.

2021-04-12 09:43 UTC, YiyunNi requested changes
Could you please revise line 5? 
"These are mostly guideline**_s_**, not rules."

2021-04-15 03:00 UTC, shengjun1985 approved these changes

2021-04-15 03:52 UTC, YiyunNi approved these changes

2021-04-16 08:00 UTC, scsven approved these changes

2021-04-16 08:00 UTC, merged