Update mergify
milvus-io/milvus pull request #5074
Opened 2021-04-27 11:50 UTC by scsven

Signed-off-by: Xiangyu Wang <xiangyu.wang@zilliz.com>

2021-04-27 11:55 UTC, jeffoverflow approved these changes, later dismissed

2021-04-28 16:48 UTC, jeffoverflow submitted a review, later dismissed

2021-04-29 01:35 UTC, neza2017 approved these changes, later dismissed

2021-04-29 01:47 UTC, czs007 approved these changes, later dismissed

2021-04-29 02:02 UTC, XuanYang-cn requested changes

2021-04-29 02:02 UTC, XuanYang-cn commented on .github/mergify.yml
>        - -title~=(?i)\[wip\]
repeated

2021-04-29 02:08 UTC, XuanYang-cn approved these changes

2021-04-29 02:17 UTC, jeffoverflow approved these changes

2021-04-29 02:17 UTC, czs007 approved these changes

2021-04-29 02:18 UTC, neza2017 approved these changes

2021-04-29 02:19 UTC, merged