Add SaveBinlogPaths grpc in dataservice
milvus-io/milvus pull request #5277
Opened 2021-05-18 07:20 UTC by congqixia

See also #5220

2021-05-18 08:31 UTC, XuanYang-cn requested changes

2021-05-18 08:31 UTC, XuanYang-cn commented on internal/dataservice/binlog_helper.go
> +// binlog helper funcsf persists binlog paths into kv storage.
Typo `funcsf`

2021-05-18 08:31 UTC, XuanYang-cn commented on internal/dataservice/binlog_helper.go
> +)
This's great.

But we don't need the comment.

2021-05-18 08:31 UTC, XuanYang-cn commented on internal/dataservice/binlog_helper.go
> +	// ErrCollectionIDNotMatch    = errors.New("collection id not matched")
Again, we don't want meaningless comment.

2021-05-18 10:31 UTC, XuanYang-cn approved these changes, later dismissed

2021-05-19 02:10 UTC, sunby approved these changes, later dismissed

2021-05-19 03:41 UTC, sunby submitted a review, later dismissed

2021-05-19 05:09 UTC, neza2017 approved these changes, later dismissed

2021-05-19 05:41 UTC, neza2017 approved these changes, later dismissed

2021-05-19 08:14 UTC, sunby submitted a review, later dismissed

2021-05-19 08:22 UTC, neza2017 submitted a review, later dismissed

2021-05-20 02:31 UTC, XuanYang-cn approved these changes

2021-05-20 02:51 UTC, sunby approved these changes

2021-05-20 02:55 UTC, neza2017 approved these changes

2021-05-20 03:34 UTC, merged