DataService publishes flush-completed message into its channel
milvus-io/milvus pull request #5320
Opened 2021-05-20 07:34 UTC by congqixia

DataService publishes flush-completed message  into related msgstream

See also: #5220 

Signed-off-by: Congqi Xia <congqi.xia@zilliz.com>

2021-05-20 07:48 UTC, XuanYang-cn requested changes

2021-05-20 07:48 UTC, XuanYang-cn commented on internal/dataservice/server.go
> +	}
I don't think this's a good solution.

Saving paths into etcd is a valid flush-completed signal. Even if we fail to publish this message, we don't need to redo the whole `consume -> buffer -> flush-> save to etcd -> publish` procedure again. We only have to re-publish this message.

2021-05-20 10:19 UTC, XuanYang-cn commented on internal/dataservice/server.go
> +	}
The recovery of publishing messages into pulsar can be accomplished in the next PR, this PR do things right if not crashed. So I approve of this change.

2021-05-20 10:22 UTC, XuanYang-cn requested changes

2021-05-20 10:31 UTC, XuanYang-cn approved these changes
Great! Thanks for your cooperation

2021-05-21 06:38 UTC, sunby approved these changes

2021-05-21 08:54 UTC, merged