Add nil check
milvus-io/milvus pull request #6832
Opened 2021-07-27 07:31 UTC by bigsheeper

Signed-off-by: bigsheeper <yihao.dai@zilliz.com>

Resolves: #6831

2021-07-27 07:35 UTC, XuanYang-cn requested changes

2021-07-27 07:35 UTC, XuanYang-cn commented on internal/datanode/meta_service.go
> +	if response != nil && response.Status.ErrorCode != commonpb.ErrorCode_Success {
It's better to use grpc functions
```go
if response.GetStatus().GetErrorCode() != commonpb.ErrorCode_Success {
    return nil, fmt.Errorf("Describe collection %v from rootcoord wrong: %s", collID, response.GetStatus().GetReason())
}
```

2021-07-27 07:37 UTC, bigsheeper commented on internal/datanode/meta_service.go
> +	if response != nil && response.Status.ErrorCode != commonpb.ErrorCode_Success {
👌

2021-07-27 07:51 UTC, XuanYang-cn commented
/lgtm

2021-07-29 11:30 UTC, XuanYang-cn commented
/lgtm

2021-07-29 11:31 UTC, XuanYang-cn commented
/unassign
/assign @czs007

2021-07-29 12:09 UTC, czs007 commented
/lgtm
/approve

2021-07-29 12:11 UTC, merged