Expose metrics of root coordinator
milvus-io/milvus pull request #7228
Opened 2021-08-23 06:52 UTC by DragonDriver

Signed-off-by: dragondriver <jiquan.long@zilliz.com>

issue: #7162

2021-08-23 06:53 UTC, DragonDriver commented
/cc @cydrain 
/cc @czs007 
/cc @scsven

2021-08-24 15:19 UTC, scsven commented
@congqixia Please review this PR.

2021-08-25 04:00 UTC, congqixia requested changes
Please fix the issues other the design ones. You could have other pr to fix design ones

2021-08-25 04:00 UTC, congqixia commented on internal/rootcoord/root_coord.go
> +	log.Debug("RootCoord.GetMetrics failed, request metric type is not implemented yet",
log message outofdate

2021-08-30 06:45 UTC, DragonDriver commented
> Please fix the issues other the design ones. You could have other pr to fix design ones

I will change the response from string to byte slice in next pr.

2021-08-30 06:49 UTC, DragonDriver commented
a little curious if there are any benchmarks that compares the efficiency of passing string or byte slice?

2021-08-30 06:53 UTC, congqixia commented
> a little curious if there are any benchmarks that compares the efficiency of passing string or byte slice?

The main issue is:  Marshaling info result is byte slice; Converting byte slice into string needs to copy whole slice which consuming extra memory and cpu time.

2021-08-30 07:02 UTC, DragonDriver commented
> > a little curious if there are any benchmarks that compares the efficiency of passing string or byte slice?
> 
> The main issue is: Marshaling info result is byte slice; Converting byte slice into string needs to copy whole slice which consuming extra memory and cpu time.

make sense. thx for pointing out this.

2021-08-30 08:54 UTC, congqixia approved these changes
/lgtm

2021-08-31 03:45 UTC, scsven commented
/approve

2021-08-31 03:45 UTC, merged