Support specified shard number when create collection
milvus-io/milvus pull request #7482
Opened 2021-09-04 11:02 UTC by czs007

Resolves: #6690 
Signed-off-by: zhenshan.cao <zhenshan.cao@zilliz.com>

2021-09-06 01:48 UTC, xiaofan-luan requested changes
We need test on create collection, then describe and check if shard information is there.

2021-09-06 01:48 UTC, xiaofan-luan commented on internal/rootcoord/task.go
> +	log.Debug("ShardsNum is ", zap.Any("shardnum", t.Req.ShardsNum))
You should at least print collection name here

2021-09-06 02:03 UTC, xiaofan-luan commented
need more unit test here to prove this patch will work, others lgtm

2021-09-06 12:39 UTC, czs007 commented
@xiaofan-luan  PTAL

2021-09-08 06:58 UTC, xiaofan-luan approved these changes

2021-09-08 06:59 UTC, xiaofan-luan commented
/approve
/lgtm

2021-09-08 07:00 UTC, merged