Update README.md
milvus-io/milvus pull request #896
Opened 2020-01-02 09:22 UTC by jielinxu

2020-01-02 09:35 UTC, yamasite requested changes
IVFLAT test report links are broken.

2020-01-04 01:20 UTC, JinHai-CN commented on docs/README.md
> +- [IVFLAT](test-report/ivfflat_test_report_cn.md)
why IVFLAT missing _cn?

2020-01-06 02:00 UTC, yamasite commented on docs/README.md
> +- [IVFLAT](test-report/ivfflat_test_report_cn.md)
Still missing _cn.

2020-01-06 02:16 UTC, jielinxu commented on docs/README.md
> +- [IVFLAT](test-report/ivfflat_test_report_cn.md)
Done

2020-01-06 02:18 UTC, yamasite approved these changes

2020-01-06 03:05 UTC, JinHai-CN approved these changes

2020-01-06 03:06 UTC, merged